# Agentic Workflows as Probabilistic Programs

LLMs are increasingly being used as agents when it comes to solving problems and tasks. These scenarios involve single or multiple LLMs interacting with the environment via tools and gathering information in order to accomplish a task or to find answer to a complex query. There are several workflows that people have come up with based on specific tasks and tools available for LLMs to use. Some notable examples include Self-Refine, Reflexion, ReAct, Magentic-One etc.

Since language models are generative, we envision these workflows to be probabilistic programs. With this perspective, we aim to separate the "what" from "how", the declarative specification of the task from how it is achieved. Now, which components of these workflows belong in "what" and which components belong in "how" is unfortunately subjective and the right choice depends on which separation opens the most uses. One perspective where everything other than the query and the final answer belongs in "how" is described in this [overleaf document](https://www.overleaf.com/read/vkkvczrnnkwb#e0fe1e)

In this note, we focus on a different perspective where a few more components than the query and the final answer make it to "what". This is primarily done to allow reasoning about a wider set of components of these agentic workflows.

## ReAct

A typical ReAct pipeline sends an LLM two prompts 

1) A system prompt that tells you what sequence of steps to follow 
2) A task prompt describing the query at hand. Upon receiving these prompts, the LLM goes through a loop of outputting thoughts and code blocks which are executed, appended to the prompt and the loop continues until final_answer is reached.

Algorithmically, it looks something like below:

```python
system_prompt = …
task = …
is_final = False
memory = task + system_prompt
while not is_final:
	thought, action = sample(LLM(.. | memory))
	is_final = check(action)
	if is_final:
		answer = extract_answer(action)
	else:
		observation = exec(action)
		memory += thought + action + observation
return answer
```

The above code is currently implemented as CodeAgent in smolagents library.

This [notebook](playground/fun.ipynb) uses CodeAgent in smolagent library to carry out a ReAct loop on the first 20 examples of GAIA benchmark. It shows 20% accuracy which varies significantly from run to run and uses on average 229,556.85 tokens per question which is a lot since the limit of context window for OpenAI API is 128,000.

## Token discrepancies

It can be confusing in smolagents that how are the statistics about input and output tokens are being generated. Atleast for OpenAI model, these token statistics printed by the library are cumulative input and output tokens totaled over all the API calls made for a query till a particular point. This differs from the length of the context passed to the single call to API.

Also, note that OpenAI APIs perform [**prompt caching**](https://developers.openai.com/api/docs/guides/prompt-caching) which can affect how the price of the tokens differ.

## Baselines

Before we move on, let's see how different LLMs perform as backbones for ReAct. 

- The following list does not include deepseek-ai/DeepSeek-R1 because it is being deprecated and not available for serverless use on TogetherAI.
- The Qwen models are being used with `{"enable_thinking": False}` as a parameter.

The two datasets being used are 
- GAIA (General AI Assistant) - 165 questions
- Fermi (Guesstimate problems) - 125 questions

In [14]:
import pickle
from pathlib import Path

import pandas as pd
from IPython.display import display

BASELINE_DIR = Path("baseline")

# Read from the per-example .pkl cache dirs rather than the .jsonl logs: evaluate_agent
# writes pickle_dir/{i}.pkl once per example index, overwritten in place on recompute, so
# each file always reflects that example's single latest result -- no de-duplication needed,
# unlike the .jsonl logs which are append-only across every run/restart across sessions.
MODEL_DIRS = {
    "gpt-4o": BASELINE_DIR / "naive_react_gpt-4o_False",
    "gpt-5.4-mini": BASELINE_DIR / "naive_react_gpt-5.4-mini_False",
    "Qwen3.7-Plus": BASELINE_DIR / "naive_react_Qwen" / "Qwen3.7-Plus_False",
    "Qwen3.5-9B": BASELINE_DIR / "naive_react_Qwen" / "Qwen3.5-9B_False",
}

# Fermi (RealFP) naive ReAct baselines -- same models, different dataset/scorer (see
# baseline/fermi_setup.py). GAIA's is_correct is an exact-match boolean; Fermi's is a
# continuous 0-1 order-of-magnitude score from fermi_scorer. summarize_results below handles
# both uniformly via float(), since True/False cast cleanly to 1.0/0.0.
FERMI_MODEL_DIRS = {
    "gpt-4o": BASELINE_DIR / "naive_fermi_gpt-4o",
    "gpt-5.4-mini": BASELINE_DIR / "naive_fermi_gpt-5.4-mini",
    "Qwen3.7-Plus": BASELINE_DIR / "naive_fermi_Qwen_Qwen3.7-Plus",
    "Qwen3.5-9B": BASELINE_DIR / "naive_fermi_Qwen_Qwen3.5-9B",
}


def summarize_results(pkl_dir: Path):
    records = []
    for pkl_file in sorted(pkl_dir.glob("*.pkl"), key=lambda p: int(p.stem)):
        with open(pkl_file, "rb") as f:
            row = pickle.load(f)
        token_counts = row.get("token_counts") or {}
        records.append({
            "is_correct": float(row.get("is_correct", False) or 0.0),
            "num_steps": row.get("num_steps", 0),
            "input_tokens": token_counts.get("input_tokens", 0),
            "output_tokens": token_counts.get("output_tokens", 0),
            "total_tokens": token_counts.get("total_tokens", 0),
            "error": row.get("error"),
        })

    n = len(records)
    if n == 0:
        return None
    correct = sum(r["is_correct"] for r in records)
    return {
        "n": n,
        "correct": correct,
        "accuracy": correct / n,
        "avg_steps": sum(r["num_steps"] for r in records) / n,
        "avg_input_tokens": sum(r["input_tokens"] for r in records) / n,
        "avg_output_tokens": sum(r["output_tokens"] for r in records) / n,
        "avg_tokens": sum(r["total_tokens"] for r in records) / n,
        "errors": sum(1 for r in records if r["error"]),
    }


def summarize_rows(model_dirs: dict):
    rows = []
    for model_name, pkl_dir in model_dirs.items():
        if not pkl_dir.exists():
            rows.append({"Model": model_name, "Accuracy": "missing dir", "Questions": 0, "Avg Steps": "-", "Avg Input Tokens": "-", "Avg Output Tokens": "-", "Avg Tokens": "-", "Errors": "-"})
            continue
        stats = summarize_results(pkl_dir)
        if stats is None:
            rows.append({"Model": model_name, "Accuracy": "no data", "Questions": 0, "Avg Steps": "-", "Avg Input Tokens": "-", "Avg Output Tokens": "-", "Avg Tokens": "-", "Errors": "-"})
            continue
        # correct is a whole number for GAIA (sum of 1.0/0.0) but fractional for Fermi (sum of
        # continuous scores) -- show 0 decimals for the former, 1 for the latter.
        correct_display = f"{stats['correct']:.0f}" if stats["correct"] == round(stats["correct"]) else f"{stats['correct']:.1f}"
        rows.append({
            "Model": model_name,
            "Accuracy": f"{correct_display}/{stats['n']} = {stats['accuracy']:.1%}",
            "Questions": stats["n"],
            "Avg Steps": f"{stats['avg_steps']:.1f}",
            "Avg Input Tokens": f"{stats['avg_input_tokens']:,.0f}",
            "Avg Output Tokens": f"{stats['avg_output_tokens']:,.0f}",
            "Avg Tokens": f"{stats['avg_tokens']:,.0f}",
            "Errors": stats["errors"],
        })
    return rows


print("=== GAIA ===")
display(pd.DataFrame(summarize_rows(MODEL_DIRS)))

print("=== Fermi ===")
display(pd.DataFrame(summarize_rows(FERMI_MODEL_DIRS)))

=== GAIA ===

,Model,Accuracy,Questions,Avg Steps,Avg Input Tokens,Avg Output Tokens,Avg Tokens,Errors
0,gpt-4o,43/165 = 26.1%,165,10.8,"134,996","1,609","136,605",0
1,gpt-5.4-mini,54/165 = 32.7%,165,5.4,"36,684",607,"37,291",0
2,Qwen3.7-Plus,103/165 = 62.4%,165,19.5,"452,400","3,028","455,429",1
3,Qwen3.5-9B,83/165 = 50.3%,165,18.9,"463,766","4,031","467,797",0

=== Fermi ===

,Model,Accuracy,Questions,Avg Steps,Avg Input Tokens,Avg Output Tokens,Avg Tokens,Errors
0,gpt-4o,71.5/125 = 57.2%,125,5.2,"40,780",666,"41,446",0
1,gpt-5.4-mini,55.3/125 = 44.2%,125,2.2,"6,495",93,"6,588",0
2,Qwen3.7-Plus,76.6/125 = 61.3%,125,16.1,"296,868","2,674","299,542",0
3,Qwen3.5-9B,69.9/125 = 55.9%,125,11.5,"173,161","2,861","176,022",0

Based on the above results, it does seem that open-source models use more tokens and more steps but are performing comparable or even better than closed source models. So maybe we should simply shift to open-source models.

## Markov ReAct

Another dimension that we wanted to test was how independent is each iteration of ReAct in comparison to the previous ones. Can the previous iterations be completely pruned and how much would this impact the performance?

In [15]:
from IPython.display import display

MARKOV_DIR = Path("markovReAct")

# Reuses summarize_results and MODEL_DIRS/FERMI_MODEL_DIRS (naive baselines) defined in the
# Baselines cell above.
CONFIG_DIRS = {
    "gpt-4o": {
        "naive": MODEL_DIRS["gpt-4o"],
        "w1": MARKOV_DIR / "markov_react_gpt-4o_w1",
        "w3": MARKOV_DIR / "markov_react_gpt-4o_w3",
        "w5": MARKOV_DIR / "markov_react_gpt-4o_w5",
    },
    "gpt-5.4-mini": {
        "naive": MODEL_DIRS["gpt-5.4-mini"],
        "w1": MARKOV_DIR / "markov_react_gpt-5.4-mini_w1",
        "w3": MARKOV_DIR / "markov_react_gpt-5.4-mini_w3",
        "w5": MARKOV_DIR / "markov_react_gpt-5.4-mini_w5",
    },
    "Qwen3.7-Plus": {
        "naive": MODEL_DIRS["Qwen3.7-Plus"],
        "w1": MARKOV_DIR / "markov_react_Qwen" / "Qwen3.7-Plus_w1",
        "w3": MARKOV_DIR / "markov_react_Qwen" / "Qwen3.7-Plus_w3",
        "w5": MARKOV_DIR / "markov_react_Qwen" / "Qwen3.7-Plus_w5",
    },
    "Qwen3.5-9B": {
        "naive": MODEL_DIRS["Qwen3.5-9B"],
        "w1": MARKOV_DIR / "markov_react_Qwen" / "Qwen3.5-9B_w1",
        "w3": MARKOV_DIR / "markov_react_Qwen" / "Qwen3.5-9B_w3",
        "w5": MARKOV_DIR / "markov_react_Qwen" / "Qwen3.5-9B_w5",
    },
}

# Fermi MarkovReAct -- same window sizes, same models, different dataset/scorer.
FERMI_CONFIG_DIRS = {
    "gpt-4o": {
        "naive": FERMI_MODEL_DIRS["gpt-4o"],
        "w1": MARKOV_DIR / "markov_fermi_gpt-4o_w1",
        "w3": MARKOV_DIR / "markov_fermi_gpt-4o_w3",
        "w5": MARKOV_DIR / "markov_fermi_gpt-4o_w5",
    },
    "gpt-5.4-mini": {
        "naive": FERMI_MODEL_DIRS["gpt-5.4-mini"],
        "w1": MARKOV_DIR / "markov_fermi_gpt-5.4-mini_w1",
        "w3": MARKOV_DIR / "markov_fermi_gpt-5.4-mini_w3",
        "w5": MARKOV_DIR / "markov_fermi_gpt-5.4-mini_w5",
    },
    "Qwen3.7-Plus": {
        "naive": FERMI_MODEL_DIRS["Qwen3.7-Plus"],
        "w1": MARKOV_DIR / "markov_fermi_Qwen_Qwen3.7-Plus_w1",
        "w3": MARKOV_DIR / "markov_fermi_Qwen_Qwen3.7-Plus_w3",
        "w5": MARKOV_DIR / "markov_fermi_Qwen_Qwen3.7-Plus_w5",
    },
    "Qwen3.5-9B": {
        "naive": FERMI_MODEL_DIRS["Qwen3.5-9B"],
        "w1": MARKOV_DIR / "markov_fermi_Qwen_Qwen3.5-9B_w1",
        "w3": MARKOV_DIR / "markov_fermi_Qwen_Qwen3.5-9B_w3",
        "w5": MARKOV_DIR / "markov_fermi_Qwen_Qwen3.5-9B_w5",
    },
}
CONFIG_ORDER = ["naive", "w1", "w3", "w5"]


def build_results_df(config_dirs: dict) -> pd.DataFrame:
    rows = []
    for model_name, configs in config_dirs.items():
        for config_name, pkl_dir in configs.items():
            stats = summarize_results(pkl_dir) if pkl_dir.exists() else None
            if stats is None:
                rows.append({"Model": model_name, "Config": config_name, "Accuracy": None, "Avg Steps": None, "Tokens (in/out/total)": None})
                continue
            rows.append({
                "Model": model_name,
                "Config": config_name,
                "Accuracy": f"{stats['accuracy']:.1%}",
                "Avg Steps": round(stats["avg_steps"], 1),
                "Tokens (in/out/total)": f"{stats['avg_input_tokens']:,.0f} / {stats['avg_output_tokens']:,.0f} / {stats['avg_tokens']:,.0f}",
            })
    return pd.DataFrame(rows)


gaia_results_df = build_results_df(CONFIG_DIRS)
fermi_results_df = build_results_df(FERMI_CONFIG_DIRS)

print("##### GAIA #####")
for metric in ["Accuracy", "Avg Steps", "Tokens (in/out/total)"]:
    print(f"=== {metric} ===")
    display(gaia_results_df.pivot(index="Model", columns="Config", values=metric)[CONFIG_ORDER])

print("\n##### Fermi (Avg Score in place of Accuracy) #####")
for metric in ["Accuracy", "Avg Steps", "Tokens (in/out/total)"]:
    print(f"=== {metric} ===")
    display(fermi_results_df.pivot(index="Model", columns="Config", values=metric)[CONFIG_ORDER])

##### GAIA #####
=== Accuracy ===

Config        naive     w1     w3     w5
Model
Qwen3.5-9B    50.3%  29.1%  33.9%  44.2%
Qwen3.7-Plus  62.4%  29.7%  54.5%  53.9%
gpt-4o        26.1%  28.5%  28.5%  30.9%
gpt-5.4-mini  32.7%  27.9%  33.9%  30.9%

=== Avg Steps ===

Config        naive    w1    w3    w5
Model
Qwen3.5-9B     18.9  30.0  26.6  24.0
Qwen3.7-Plus   19.5  32.6  24.7  22.4
gpt-4o         10.8  21.0  13.4  11.9
gpt-5.4-mini    5.4   8.6   5.2   5.0

=== Tokens (in/out/total) ===

Config,naive,w1,w3,w5
Model,,,,
Qwen3.5-9B,"463,766 / 4,031 / 467,797","127,817 / 5,344 / 133,161","183,237 / 5,284 / 188,521","218,227 / 4,544 / 222,771"
Qwen3.7-Plus,"452,400 / 3,028 / 455,429","133,445 / 3,706 / 137,151","168,823 / 3,336 / 172,159","206,597 / 3,088 / 209,685"
gpt-4o,"134,996 / 1,609 / 136,605","81,046 / 2,650 / 83,697","79,174 / 1,954 / 81,128","86,789 / 1,618 / 88,407"
gpt-5.4-mini,"36,684 / 607 / 37,291","31,276 / 986 / 32,263","24,328 / 563 / 24,891","27,341 / 577 / 27,918"

##### Fermi (Avg Score in place of Accuracy) #####
=== Accuracy ===

Config        naive     w1     w3     w5
Model
Qwen3.5-9B    55.9%  54.6%  52.5%  58.5%
Qwen3.7-Plus  61.3%  51.5%  55.1%  55.4%
gpt-4o        57.2%  59.5%  55.6%  57.9%
gpt-5.4-mini  44.2%  42.5%  45.1%  39.2%

=== Avg Steps ===

Config        naive    w1    w3    w5
Model
Qwen3.5-9B     11.5  21.0  16.8  14.3
Qwen3.7-Plus   16.1  21.7  20.6  17.8
gpt-4o          5.2   4.8   4.2   4.5
gpt-5.4-mini    2.2   2.2   2.2   2.2

=== Tokens (in/out/total) ===

Config,naive,w1,w3,w5
Model,,,,
Qwen3.5-9B,"173,161 / 2,861 / 176,022","86,114 / 2,867 / 88,980","106,039 / 2,978 / 109,017","118,734 / 2,781 / 121,515"
Qwen3.7-Plus,"296,868 / 2,674 / 299,542","90,431 / 2,030 / 92,461","128,061 / 2,310 / 130,371","140,663 / 2,336 / 142,999"
gpt-4o,"40,780 / 666 / 41,446","17,249 / 657 / 17,907","20,246 / 560 / 20,806","24,687 / 612 / 25,299"
gpt-5.4-mini,"6,495 / 93 / 6,588","6,326 / 82 / 6,408","6,348 / 95 / 6,443","6,455 / 98 / 6,553"

The above results are very interesting as they show how the number of steps are more in Markov ReAct but the token counts are low. It turns out the source of low token counts is low input tokens. And in fact, the output tokens are higher in Markov ReAct than naive ReAct.

It is also worth noting that for gpt-4o and gpt-5.4-mini, naiveReAct is not the most accurate version which indicates to possibility of improving performance when the context is cleverly chosen.

## Quantifying Redundancies in Steps

In this [notebook](step_independence/step_independence.ipynb), we go through all the trajectories and ask "gpt-4o-mini" to judge whether the steps were redundant. We got the following results:

In [16]:
import json

STEP_INDEPENDENCE_DIR = Path("step_independence")

# Reuses CONFIG_DIRS/FERMI_CONFIG_DIRS (model -> {naive/w1/w3/w5: pkl_dir}) and CONFIG_ORDER
# defined in the Markov ReAct cell above.

def load_redundant_pairs(model_name: str, config_name: str, prefix: str = "") -> list[dict]:
    key = model_name if config_name == "naive" else f"{model_name}_{config_name}"
    path = STEP_INDEPENDENCE_DIR / f"redundant_pairs_{prefix}{key}.json"
    if not path.exists():
        return []
    with open(path) as f:
        data = json.load(f)
    return data.get("findings", [])


def total_pairs(pkl_dir: Path) -> int:
    """Total number of consecutive step-pairs across every trajectory in pkl_dir."""
    total = 0
    for pkl_file in pkl_dir.glob("*.pkl"):
        with open(pkl_file, "rb") as f:
            traj = pickle.load(f)
        total += max(0, traj.get("num_steps", 0) - 1)
    return total


def build_redundancy_df(config_dirs: dict, prefix: str = "") -> pd.DataFrame:
    rows = []
    for model_name, configs in config_dirs.items():
        for config_name, pkl_dir in configs.items():
            n_redundant = len(load_redundant_pairs(model_name, config_name, prefix))
            n_total = total_pairs(pkl_dir) if pkl_dir.exists() else 0
            rows.append({
                "Model": model_name,
                "Config": config_name,
                "Redundant Pairs": n_redundant,
                "% Redundant": round(100 * n_redundant / n_total, 1) if n_total else None,
            })
    return pd.DataFrame(rows)


redundancy_df = build_redundancy_df(CONFIG_DIRS)
fermi_redundancy_df = build_redundancy_df(FERMI_CONFIG_DIRS, prefix="fermi_")

print("##### GAIA #####")
for metric in ["Redundant Pairs", "% Redundant"]:
    print(f"=== {metric} ===")
    display(redundancy_df.pivot(index="Model", columns="Config", values=metric)[CONFIG_ORDER])

print("\n##### Fermi #####")
for metric in ["Redundant Pairs", "% Redundant"]:
    print(f"=== {metric} ===")
    display(fermi_redundancy_df.pivot(index="Model", columns="Config", values=metric)[CONFIG_ORDER])

##### GAIA #####
=== Redundant Pairs ===

Config        naive    w1    w3   w5
Model
Qwen3.5-9B      632  1350  1096  908
Qwen3.7-Plus    710  2053  1124  950
gpt-4o          381   796   470  393
gpt-5.4-mini    118   222    96   93

=== % Redundant ===

Config        naive    w1    w3    w5
Model
Qwen3.5-9B     21.4  28.3  26.0  23.9
Qwen3.7-Plus   23.3  39.3  28.7  27.0
gpt-4o         23.5  24.1  22.9  21.9
gpt-5.4-mini   16.1  17.7  14.0  14.0

##### Fermi #####
=== Redundant Pairs ===

Config        naive   w1   w3   w5
Model
Qwen3.5-9B      228  995  510  363
Qwen3.7-Plus    324  833  568  426
gpt-4o          130   89   93   78
gpt-5.4-mini     32   31   36   32

=== % Redundant ===

Config        naive    w1    w3    w5
Model
Qwen3.5-9B     17.3  39.7  25.8  21.8
Qwen3.7-Plus   17.2  32.1  23.1  20.3
gpt-4o         25.0  18.5  23.1  17.9
gpt-5.4-mini   20.9  20.1  24.0  21.3

Based on the numbers above, it seems that for Qwen models, as you prune the context, the relative redundancy increases. The same does not hold for gpt models, apparently window context 3 and 5 have lower relative redundancies compared to full context.

It also seems that there might be some correlation between accuracy and redundancy:

In [17]:
# Reuses CONFIG_DIRS/FERMI_CONFIG_DIRS, summarize_results, and redundancy_df/fermi_redundancy_df
# from the cells above.

def build_corr_df(config_dirs: dict, redundancy_df: pd.DataFrame) -> pd.DataFrame:
    accuracy_rows = []
    for model_name, configs in config_dirs.items():
        for config_name, pkl_dir in configs.items():
            stats = summarize_results(pkl_dir) if pkl_dir.exists() else None
            accuracy_rows.append({
                "Model": model_name,
                "Config": config_name,
                "Accuracy": stats["accuracy"] if stats else None,
            })
    accuracy_df = pd.DataFrame(accuracy_rows)
    return redundancy_df.merge(accuracy_df, on=["Model", "Config"])


gaia_corr_df = build_corr_df(CONFIG_DIRS, redundancy_df)
fermi_corr_df = build_corr_df(FERMI_CONFIG_DIRS, fermi_redundancy_df)

print("GAIA -- per-model correlation (accuracy vs. % redundant), n=4 configs (naive, w1, w3, w5) each:")
for model_name, group in gaia_corr_df.groupby("Model"):
    corr = group["Accuracy"].corr(group["% Redundant"])
    print(f"  {model_name}: r = {corr:.3f}")

print("\nFermi -- per-model correlation (avg score vs. % redundant), n=4 configs (naive, w1, w3, w5) each:")
for model_name, group in fermi_corr_df.groupby("Model"):
    corr = group["Accuracy"].corr(group["% Redundant"])
    print(f"  {model_name}: r = {corr:.3f}")

GAIA -- per-model correlation (accuracy vs. % redundant), n=4 configs (naive, w1, w3, w5) each:
  Qwen3.5-9B: r = -0.988
  Qwen3.7-Plus: r = -0.992
  gpt-4o: r = -0.696
  gpt-5.4-mini: r = -0.706

Fermi -- per-model correlation (avg score vs. % redundant), n=4 configs (naive, w1, w3, w5) each:
  Qwen3.5-9B: r = -0.372
  Qwen3.7-Plus: r = -0.900
  gpt-4o: r = -0.676
  gpt-5.4-mini: r = 0.460

As you can see above, apparently there is a strong negative correlation for GAIA between accuracy and the percentage of redundant step-pairs, suggesting that models with fewer redundant steps tend to perform better on the task.

Results for Fermi are weird I don't get it.

However, the correlation above is computed at the level of (model, config) aggregates (n=4 points per model). Let's check whether the same relationship holds at the level of individual questions -- for each (model, config), correlate `is_correct` against that question's own fraction of redundant step-pairs:

In [18]:
from collections import Counter

# Reuses CONFIG_DIRS, FERMI_CONFIG_DIRS, CONFIG_ORDER, and load_redundant_pairs from the cells above.

def question_level_stats(model_name: str, config_name: str, pkl_dir: Path, prefix: str = "") -> list[dict]:
    """One row per question in this (model, config): its score (float -- 1.0/0.0 for GAIA's
    exact-match boolean, continuous 0-1 for Fermi), and the fraction of its own consecutive
    step-pairs the judge flagged as redundant."""
    findings = load_redundant_pairs(model_name, config_name, prefix)
    redundant_counts = Counter(f["task_id"] for f in findings)

    rows = []
    for pkl_file in pkl_dir.glob("*.pkl"):
        with open(pkl_file, "rb") as f:
            traj = pickle.load(f)
        task_id = traj.get("task_id", "?")
        n_pairs = max(0, traj.get("num_steps", 0) - 1)
        if n_pairs == 0:
            continue
        rows.append({
            "is_correct": float(traj.get("is_correct", False) or 0.0),
            "fraction_redundant": redundant_counts.get(task_id, 0) / n_pairs,
        })
    return rows


def build_question_corr_df(config_dirs: dict, prefix: str = "") -> pd.DataFrame:
    rows = []
    for model_name, configs in config_dirs.items():
        for config_name, pkl_dir in configs.items():
            if not pkl_dir.exists():
                continue
            qrows = question_level_stats(model_name, config_name, pkl_dir, prefix)
            qdf = pd.DataFrame(qrows)
            corr = qdf["is_correct"].corr(qdf["fraction_redundant"])
            rows.append({"Model": model_name, "Config": config_name, "r": round(corr, 3)})
    return pd.DataFrame(rows)


gaia_question_corr_df = build_question_corr_df(CONFIG_DIRS)
fermi_question_corr_df = build_question_corr_df(FERMI_CONFIG_DIRS, prefix="fermi_")

print("##### GAIA #####")
display(gaia_question_corr_df.pivot(index="Model", columns="Config", values="r")[CONFIG_ORDER])

print("\n##### Fermi #####")
display(fermi_question_corr_df.pivot(index="Model", columns="Config", values="r")[CONFIG_ORDER])

##### GAIA #####

Config        naive     w1     w3     w5
Model
Qwen3.5-9B   -0.085 -0.225 -0.208 -0.328
Qwen3.7-Plus -0.151 -0.445 -0.308 -0.263
gpt-4o        0.048 -0.055 -0.093  0.015
gpt-5.4-mini  0.001 -0.079 -0.041  0.025

##### Fermi #####

Config        naive     w1     w3     w5
Model
Qwen3.5-9B   -0.148 -0.343 -0.098 -0.230
Qwen3.7-Plus -0.256 -0.318 -0.158 -0.239
gpt-4o        0.094  0.127  0.191 -0.049
gpt-5.4-mini -0.152 -0.164 -0.307 -0.206

## Probabilistic ReAct

A typical ReAct workflow struggles with various shortcomings, namely
1. The context-length becomes a bottleneck as all triplets of (thought, action and observation) are added to the context indiscriminately.
    a. And markov ReAct was an attempt to evaluate the impact of truncating the context
2. The uncertainty is never handled explicitly making it difficult for the responses to be reliable
3. There is no modularity, it is essentially a continuous global sequence of thoughts, actions and observations.

Essentially, the first and foremost goal is to introduce structure in ReAct in the form of a probabilistic program. I made two attempts to do so: ProbabilisticAgent and ContextPruningAgent, but they both suffer with issues and I won't be describing them for now (TODO).

For now, we plan to try the following algorithm:

```python
system_prompt = …
task = …
is_final = False
memory = task + system_prompt
while not is_final:
    # Sample an action specification from the language model
    thought, action_spec = sample(LLM(.. | memory))
    # Sample n actions using the action specification
    fill_in = sample(LLM(.. | memory + thought + action_spec + "fill in the specification"), n)
    actions = action_spec[fill_in]
    results = execute(actions)
    # Use LLM-as-a-judge to pick which step makes the most progress
    feedback = sample(LLM(.. | task + thought + actions + results + "Look at these {n} pairs of thought action and results and rank them"))
    final_thought, final_action_spec, final_fill_in, final_result = select(feedback, thought, action_spec, fill_in, results)
	is_final = check(final_action_spec)
	if is_final:
		answer = extract_answer(action)
	else:
		memory += final_thought + final_action_spec + final_fill_in + final_result
return answer
```

### Meta-Analysis of Probabilistic ReAct

Currently each iteration of Probabilistic ReAct is making $n$ calls to an LLM API, one to get action specification, one to get multiple fill-ins and one for judging the results. That can be too many LLM calls leading to more expense on tokens; but it can potentially help in keeping the context length low.

Anyways, my hypothesis for Probabilistic ReAct is that since at every step, it chooses the best-of-n and is simulating a beam search, its performance should be strictly better than naive ReAct.

### Implementation of Probabilistic ReAct

The approach is current implemented as [TraceletCodeAgent](src/smolagents/tracelet_agent.py) and I describe the three LLM calls below:

1. **Sampling Specification**: We ask the LLM to output a templated action (in direct_prompt) or ask it to output a normal action and then we templatize it (in post_process)
2. **Filling in**: We ask the LLM to generate fillins in a structured format
3. **LLM as a judge**: We pass only the initial task, the actions and the corresponding results to an LLM to pick the best one

Results below: direct_prompt for all four models (Qwen3.7-Plus's rerun is still partial at 37/165, so its row is scored on those 37 questions), then the partial post_process runs.

In [19]:
NAIVE_DIRS = {
    "gpt-4o": MODEL_DIRS["gpt-4o"],
    "gpt-5.4-mini": MODEL_DIRS["gpt-5.4-mini"],
    "Qwen3.5-9B": MODEL_DIRS["Qwen3.5-9B"],
    "Qwen3.7-Plus": BASELINE_DIR / "naive_react_Qwen" / "Qwen3.7-Plus_False",
}
TRACELET_DIRECT_DIRS = {
    "gpt-4o": BASELINE_DIR / "tracelet_direct_react_gpt-4o",
    "gpt-5.4-mini": BASELINE_DIR / "tracelet_direct_react_gpt-5.4-mini",
    "Qwen3.5-9B": BASELINE_DIR / "tracelet_direct_react_Qwen" / "Qwen3.5-9B",
    "Qwen3.7-Plus": BASELINE_DIR / "tracelet_direct_react_Qwen" / "Qwen3.7-Plus",
}

# Unlike summarize_results (which reads every *.pkl in a dir), this reads a fixed range of
# indices so two runs at different stages of completion can be compared on the exact same
# subset of questions -- Qwen3.7-Plus's rerun is only at 37/165, so its row compares against
# naiveReAct on those same first 37 questions while the other three compare on all 165.
def summarize_first_n(pkl_dir: Path, n: int) -> dict:
    records = []
    for i in range(n):
        with open(pkl_dir / f"{i}.pkl", "rb") as f:
            records.append(pickle.load(f))
    correct = sum(1 for r in records if r.get("is_correct"))
    return {
        "n": n,
        "correct": correct,
        "accuracy": correct / n,
        "avg_steps": sum(r.get("num_steps", 0) for r in records) / n,
        "avg_tokens": sum(r["token_counts"].get("total_tokens", 0) for r in records) / n,
        "max_steps_hits": sum(1 for r in records if r.get("num_steps", 0) >= 51),
    }


def build_table(dirs: dict, n_common_by_model: dict) -> pd.DataFrame:
    rows = []
    for model_name, pkl_dir in dirs.items():
        stats = summarize_first_n(pkl_dir, n_common_by_model[model_name])
        rows.append({
            "Model": model_name,
            "Accuracy": f"{stats['correct']}/{stats['n']} = {stats['accuracy']:.1%}",
            "Avg Steps": f"{stats['avg_steps']:.1f}",
            "Avg Tokens": f"{stats['avg_tokens']:,.0f}",
            "Hit max_steps (51)": stats["max_steps_hits"],
        })
    return pd.DataFrame(rows).set_index("Model")


# Same subset of questions for both tables per model, in case the Tracelet sweep for a
# given model isn't fully caught up yet.
n_common_by_model = {m: len(list(d.glob("*.pkl"))) for m, d in TRACELET_DIRECT_DIRS.items()}

# The n_samples=1 ablation is at a different stage of completion per model, so it gets its own
# subset sizes and its own matched naiveReAct table rather than reusing n_common_by_model above.
TRACELET_DIRECT_N1_DIRS = {
    "gpt-4o": BASELINE_DIR / "tracelet_direct_n1_react_gpt-4o",
    "gpt-5.4-mini": BASELINE_DIR / "tracelet_direct_n1_react_gpt-5.4-mini",
    "Qwen3.5-9B": BASELINE_DIR / "tracelet_direct_n1_react_Qwen" / "Qwen3.5-9B",
    "Qwen3.7-Plus": BASELINE_DIR / "tracelet_direct_n1_react_Qwen" / "Qwen3.7-Plus",
}
n1_common_by_model = {m: len(list(d.glob("*.pkl"))) for m, d in TRACELET_DIRECT_N1_DIRS.items()}

print("=== naiveReAct (matched to the n_samples=1 subsets) ===")
display(build_table(NAIVE_DIRS, n1_common_by_model))

print("=== Tracelet (direct_prompt, n_samples=1) ===")
display(build_table(TRACELET_DIRECT_N1_DIRS, n1_common_by_model))

# post_process coverage is partial and heterogeneous -- gpt-4o's sweep stopped at 12 questions, and the
# only other post_process run is Qwen3.7-Plus at n_samples=1 -- so each is paired with its own naiveReAct
# baseline over its own matched subset rather than dropped into the table above.
TRACELET_POSTPROCESS_RUNS = {
    "gpt-4o (n=3)": (BASELINE_DIR / "tracelet_react_gpt-4o", MODEL_DIRS["gpt-4o"]),
    "Qwen3.7-Plus (n=1)": (
        BASELINE_DIR / "tracelet_postprocess_n1_react_Qwen" / "Qwen3.7-Plus",
        BASELINE_DIR / "naive_react_Qwen" / "Qwen3.7-Plus_False",
    ),
}

postprocess_rows = []
for label, (pp_dir, naive_dir) in TRACELET_POSTPROCESS_RUNS.items():
    n = len(list(pp_dir.glob("*.pkl")))
    pp, naive = summarize_first_n(pp_dir, n), summarize_first_n(naive_dir, n)
    postprocess_rows.append({
        "Config": label,
        "Questions": n,
        "naive Accuracy": f"{naive['correct']}/{n} = {naive['accuracy']:.1%}",
        "post_process Accuracy": f"{pp['correct']}/{n} = {pp['accuracy']:.1%}",
        "naive Steps": f"{naive['avg_steps']:.1f}",
        "post_process Steps": f"{pp['avg_steps']:.1f}",
        "naive Tokens": f"{naive['avg_tokens']:,.0f}",
        "post_process Tokens": f"{pp['avg_tokens']:,.0f}",
        "post_process hit max_steps": pp["max_steps_hits"],
    })

print("\n=== Tracelet (post_process) vs naiveReAct, each on its own matched subset ===")
display(pd.DataFrame(postprocess_rows).set_index("Config"))

=== naiveReAct (matched to the n_samples=1 subsets) ===

                    Accuracy Avg Steps Avg Tokens  Hit max_steps (51)
Model
gpt-4o        43/165 = 26.1%      10.8    136,605                   5
gpt-5.4-mini  54/165 = 32.7%       5.4     37,291                   1
Qwen3.5-9B     35/64 = 54.7%      18.1    409,701                   6
Qwen3.7-Plus   28/50 = 56.0%      20.1    466,413                   6

=== Tracelet (direct_prompt, n_samples=1) ===

                    Accuracy Avg Steps Avg Tokens  Hit max_steps (51)
Model
gpt-4o        42/165 = 25.5%      18.2    369,365                  17
gpt-5.4-mini  47/165 = 28.5%      13.8    278,993                  14
Qwen3.5-9B     22/64 = 34.4%      29.5    457,844                  27
Qwen3.7-Plus   13/50 = 26.0%      34.4  1,088,872                  27

=== Tracelet (post_process) vs naiveReAct, each on its own matched subset ===

,Questions,naive Accuracy,post_process Accuracy,naive Steps,post_process Steps,naive Tokens,post_process Tokens,post_process hit max_steps
Config,,,,,,,,
gpt-4o (n=3),12,3/12 = 25.0%,2/12 = 16.7%,14.1,20.2,"204,702","405,611",2
Qwen3.7-Plus (n=1),50,28/50 = 56.0%,8/50 = 16.0%,20.1,40.0,"466,413","925,362",30

Ok, so from the results above, it is very clear that Tracelet (with n=1) does not perform as well as naiveReAct which is concerning since it should have performed competitively. It is just naiveReAct with some additional bells and whistles. I spent few days concerned about bells and whistles being implemented to cover as many failure cases as possible.
- made sure memory was updated appropriately
- fillins had fallbacks
- there were sentinels in the produced code

But it also seems that since we never changed the `system prompt`, the model doesn't know what is happening. So yes, in the next step, let's write a suitable system prompt and actually change TraceletReAct into something where the model knows what is happening.

### Probabilistic ReAct v3: protocol prompt + snapshot commit

The accuracy drop diagnosed above was fixed by three changes (2026-08-24/25):

1. **Protocol system prompt** (`src/smolagents/prompts/tracelet_agent.yaml`, passed via `prompt_templates=`): teaches the template/fill-in cycle with rewritten few-shot examples (sentinelized tool calls + `Fill-in:` blocks), plus a verify-first rule that stopped gpt-5.4-mini from answering from priors in one step (28% → 42% on the first 50).
2. **Memory replays the protocol**: `model_output` records the skeleton + chosen `Fill-in:` lines instead of the substituted code, so the model's own history keeps demonstrating the format (without this, sentinel emission decays over the trajectory).
3. **Snapshot commit**: the judged winner is committed from its trial's saved executor state instead of being re-executed. The old double execution corrupted stateful-tool observations (`page_down` advanced two pages per step, so the model read every other page).

The table below compares naiveReAct against this v3 configuration (`direct_prompt`, `n_samples=1` -- the ablation, so parity with naive is the expected result; best-of-n gains would come from n>1, not yet rerun). Each pair is scored on the same first-N questions, where N is however many the (possibly still-running) v3 sweep has completed for that model.

In [20]:
# Reuses BASELINE_DIR, summarize_first_n, pd, and display from the cells above.

TRACELET_V3_DIRS = {
    "gpt-4o": BASELINE_DIR / "tracelet_direct_n1_tp_v3_react_gpt-4o",
    "gpt-5.4-mini": BASELINE_DIR / "tracelet_direct_n1_tp_v3_react_gpt-5.4-mini",
    "Qwen3.5-9B": BASELINE_DIR / "tracelet_direct_n1_tp_v3_react_Qwen" / "Qwen3.5-9B",
    "Qwen3.7-Plus": BASELINE_DIR / "tracelet_direct_n1_tp_v3_react_Qwen" / "Qwen3.7-Plus",
}
V3_NAIVE_DIRS = {
    "gpt-4o": BASELINE_DIR / "naive_react_gpt-4o_False",
    "gpt-5.4-mini": BASELINE_DIR / "naive_react_gpt-5.4-mini_False",
    "Qwen3.5-9B": BASELINE_DIR / "naive_react_Qwen" / "Qwen3.5-9B_False",
    "Qwen3.7-Plus": BASELINE_DIR / "naive_react_Qwen" / "Qwen3.7-Plus_False",
}

v3_rows = []
for model_name, v3_dir in TRACELET_V3_DIRS.items():
    naive_dir = V3_NAIVE_DIRS[model_name]
    # Matched first-N subset per model: N = whatever the (possibly still-running) v3 sweep has finished.
    n = min(len(list(v3_dir.glob("*.pkl"))), len(list(naive_dir.glob("*.pkl")))) if v3_dir.exists() else 0
    if n == 0:
        v3_rows.append({"Model": model_name, "Questions": 0, "naive Accuracy": "no data", "prob Accuracy": "no data"})
        continue
    naive, prob = summarize_first_n(naive_dir, n), summarize_first_n(v3_dir, n)
    v3_rows.append({
        "Model": model_name,
        "Questions": n,
        "naive Accuracy": f"{naive['correct']}/{n} = {naive['accuracy']:.1%}",
        "prob Accuracy": f"{prob['correct']}/{n} = {prob['accuracy']:.1%}",
        "naive Steps": f"{naive['avg_steps']:.1f}",
        "prob Steps": f"{prob['avg_steps']:.1f}",
        "naive Tokens": f"{naive['avg_tokens']:,.0f}",
        "prob Tokens": f"{prob['avg_tokens']:,.0f}",
        # How much more the probabilistic version spends per question than naive.
        "Token Increase": (
            f"{prob['avg_tokens'] / naive['avg_tokens']:.1f}x (+{100 * (prob['avg_tokens'] / naive['avg_tokens'] - 1):.0f}%)"
            if naive["avg_tokens"]
            else "-"
        ),
    })

display(pd.DataFrame(v3_rows).set_index("Model"))

,Questions,naive Accuracy,prob Accuracy,naive Steps,prob Steps,naive Tokens,prob Tokens,Token Increase
Model,,,,,,,,
gpt-4o,165,43/165 = 26.1%,38/165 = 23.0%,10.8,12.9,"136,605","415,569",3.0x (+204%)
gpt-5.4-mini,165,54/165 = 32.7%,50/165 = 30.3%,5.4,9.5,"37,291","329,657",8.8x (+784%)
Qwen3.5-9B,165,83/165 = 50.3%,68/165 = 41.2%,18.9,21.5,"467,797","916,970",2.0x (+96%)
Qwen3.7-Plus,165,103/165 = 62.4%,95/165 = 57.6%,19.5,21.1,"455,429","1,067,848",2.3x (+134%)

Ok, so it seems that gpt-5.4-mini is consuming a lot more tokens in comparison and Qwen models are performing worse. Let's try to fix that. So the following changes have been made:

1. The thought is also being passed to the fill in call. There was a bug there.
2. The html pulled from online now is not raw html but well formatted documents. 

After these changes, below we have the updated numbers.

In [21]:
# Reuses BASELINE_DIR, summarize_first_n, pickle, pd, and display from the cells above.
from math import comb

V5_DIRS = {
    "gpt-4o": BASELINE_DIR / "tracelet_direct_n1_tp_v5_react_gpt-4o",
    "gpt-5.4-mini": BASELINE_DIR / "tracelet_direct_n1_tp_v5_react_gpt-5.4-mini",
    "Qwen3.5-9B": BASELINE_DIR / "tracelet_direct_n1_tp_v5_react_Qwen" / "Qwen3.5-9B",
    "Qwen3.7-Plus": BASELINE_DIR / "tracelet_direct_n1_tp_v5_react_Qwen" / "Qwen3.7-Plus",
}
V5_NAIVE_DIRS = {
    "gpt-4o": BASELINE_DIR / "naive_react_gpt-4o_False_fixedbrowser",
    "gpt-5.4-mini": BASELINE_DIR / "naive_react_gpt-5.4-mini_False_fixedbrowser",
    "Qwen3.5-9B": BASELINE_DIR / "naive_react_Qwen" / "Qwen3.5-9B_False_fixedbrowser",
    "Qwen3.7-Plus": BASELINE_DIR / "naive_react_Qwen" / "Qwen3.7-Plus_False_fixedbrowser",
}


def contiguous_prefix(pkl_dir: Path) -> int:
    """Longest run 0..k-1 present -- a still-running sweep has gaps, and indexing past one raises."""
    have = {int(p.stem) for p in pkl_dir.glob("*.pkl")}
    k = 0
    while k in have:
        k += 1
    return k


def correctness(pkl_dir: Path, n: int) -> list[bool]:
    flags = []
    for i in range(n):
        with open(pkl_dir / f"{i}.pkl", "rb") as f:
            flags.append(bool(pickle.load(f).get("is_correct")))
    return flags


def error_count(pkl_dir: Path, n: int) -> int:
    """Provider failures score as incorrect, so an asymmetric count skews the comparison."""
    total = 0
    for i in range(n):
        with open(pkl_dir / f"{i}.pkl", "rb") as f:
            total += bool(pickle.load(f).get("error"))
    return total


def mcnemar(a: list[bool], b: list[bool]) -> tuple[int, int, float]:
    """Exact two-sided McNemar over the discordant pairs only."""
    x = sum(1 for p, q in zip(a, b) if p and not q)
    y = sum(1 for p, q in zip(a, b) if q and not p)
    if x + y == 0:
        return x, y, 1.0
    return x, y, min(2 * sum(comb(x + y, k) for k in range(min(x, y) + 1)) / 2 ** (x + y), 1.0)


v5_rows = []
for model_name, v5_dir in V5_DIRS.items():
    naive_dir = V5_NAIVE_DIRS[model_name]
    if not v5_dir.exists() or not naive_dir.exists():
        v5_rows.append({"Model": model_name, "Questions": 0, "naive Accuracy": "no run", "v5 Accuracy": "no run"})
        continue
    n = min(contiguous_prefix(v5_dir), contiguous_prefix(naive_dir))
    if n == 0:
        v5_rows.append({"Model": model_name, "Questions": 0, "naive Accuracy": "no data", "v5 Accuracy": "no data"})
        continue
    naive, v5 = summarize_first_n(naive_dir, n), summarize_first_n(v5_dir, n)
    n_only, v5_only, p = mcnemar(correctness(naive_dir, n), correctness(v5_dir, n))
    v5_rows.append({
        "Model": model_name,
        "Questions": n,
        "naive Accuracy": f"{naive['correct']}/{n} = {naive['accuracy']:.1%}",
        "v5 Accuracy": f"{v5['correct']}/{n} = {v5['accuracy']:.1%}",
        "naive Steps": f"{naive['avg_steps']:.1f}",
        "v5 Steps": f"{v5['avg_steps']:.1f}",
        "naive Tokens": f"{naive['avg_tokens']:,.0f}",
        "v5 Tokens": f"{v5['avg_tokens']:,.0f}",
        "Token Increase": f"{v5['avg_tokens'] / naive['avg_tokens']:.1f}x" if naive["avg_tokens"] else "-",
        "Discordant naive/v5": f"{n_only}/{v5_only}",
        "McNemar p": f"{p:.3f}",
        "Errors naive/v5": f"{error_count(naive_dir, n)}/{error_count(v5_dir, n)}",
    })

print("=== naiveReAct vs Probabilistic ReAct v5 -- both on the FIXED browser, matched subsets ===")
display(pd.DataFrame(v5_rows).set_index("Model"))

=== naiveReAct vs Probabilistic ReAct v5 -- both on the FIXED browser, matched subsets ===

,Questions,naive Accuracy,v5 Accuracy,naive Steps,v5 Steps,naive Tokens,v5 Tokens,Token Increase,Discordant naive/v5,McNemar p,Errors naive/v5
Model,,,,,,,,,,,
gpt-4o,165,56/165 = 33.9%,41/165 = 24.8%,8.2,12.3,"76,848","319,790",4.2x,24/9,0.014,0/0
gpt-5.4-mini,165,53/165 = 32.1%,55/165 = 33.3%,5.0,7.7,"26,707","167,116",6.3x,17/19,0.868,0/0
Qwen3.5-9B,165,79/165 = 47.9%,79/165 = 47.9%,17.0,18.1,"372,615","620,765",1.7x,24/24,1.000,0/0
Qwen3.7-Plus,165,109/165 = 66.1%,101/165 = 61.2%,16.1,17.1,"320,795","712,536",2.2x,21/13,0.229,1/0

An observation that has come up is that the runs reported above might have had leaked answers from accessing huggingface. The following code apparently counts where the leak wasn't there.

In [22]:
# Reuses BASELINE_DIR, V5_DIRS, V5_NAIVE_DIRS, mcnemar, pickle, pd and display from the cells above.
import sys

sys.path.insert(0, str(BASELINE_DIR))
from benchmark_leak_filter import leak_reason  # noqa: E402

LEAK_ARMS = {m: (V5_NAIVE_DIRS[m], V5_DIRS[m]) for m in V5_DIRS}


def leak_step(row) -> str | None:
    """First step whose tool output looks like a benchmark answer-key dump, else None."""
    for step in row.get("steps") or []:
        obs = step.get("observations")
        if not isinstance(obs, str):
            continue
        # Search results embed their URLs inline, so the same text feeds both pattern sets.
        reason = leak_reason(url=obs, text=obs)
        if reason:
            return f"step {step.get('step_number')}: {reason}"
    return None


def load_arm(pkl_dir):
    rows = {}
    for p in pkl_dir.glob("*.pkl"):
        with open(p, "rb") as f:
            row = pickle.load(f)
        rows[int(p.stem)] = {
            "correct": bool(row.get("is_correct")),
            "error": bool(row.get("error")),
            "leak": leak_step(row),
        }
    return rows


leak_rows, leak_detail = [], {}
for model_name, (naive_dir, v5_dir) in LEAK_ARMS.items():
    if not naive_dir.exists() or not v5_dir.exists():
        continue
    naive, v5 = load_arm(naive_dir), load_arm(v5_dir)
    shared = sorted(set(naive) & set(v5))
    # An error scores as incorrect, so drop it in either arm before comparing anything.
    full = [i for i in shared if not naive[i]["error"] and not v5[i]["error"]]
    leaked = [i for i in full if naive[i]["leak"] or v5[i]["leak"]]
    clean = [i for i in full if i not in set(leaked)]
    leak_detail[model_name] = [
        (i, naive[i]["correct"], v5[i]["correct"], naive[i]["leak"], v5[i]["leak"]) for i in leaked
    ]

    row = {"Model": model_name}
    for label, keep in (("full", full), ("clean", clean)):
        if not keep:
            row[f"n {label}"] = 0
            row[f"naive {label}"] = row[f"v5 {label}"] = row[f"disc {label}"] = "-"
            continue
        nc = sum(naive[i]["correct"] for i in keep)
        vc = sum(v5[i]["correct"] for i in keep)
        x, y, _ = mcnemar([naive[i]["correct"] for i in keep], [v5[i]["correct"] for i in keep])
        row[f"n {label}"] = len(keep)
        row[f"naive {label}"] = f"{nc}/{len(keep)} = {nc / len(keep):.1%}"
        row[f"v5 {label}"] = f"{vc}/{len(keep)} = {vc / len(keep):.1%}"
        row[f"disc {label}"] = f"{x}/{y}"
    leak_rows.append(row)

print("=== naive vs v5, restricted to questions where NEITHER arm saw an answer-key page ===")
print("Both arms ran with the leak filter OFF, so leaked pages were reachable in either.")
print("'full' = every question clean of provider errors; 'clean' = also leak-free in both arms.")
print("leak_detail[model] lists the excluded questions: (index, naive correct, v5 correct, reasons).")
cols = ["n full", "naive full", "v5 full", "disc full",
        "n clean", "naive clean", "v5 clean", "disc clean"]
display(pd.DataFrame(leak_rows).set_index("Model")[cols])

=== naive vs v5, restricted to questions where NEITHER arm saw an answer-key page ===
Both arms ran with the leak filter OFF, so leaked pages were reachable in either.
'full' = every question clean of provider errors; 'clean' = also leak-free in both arms.
leak_detail[model] lists the excluded questions: (index, naive correct, v5 correct, reasons).

,n full,naive full,v5 full,disc full,n clean,naive clean,v5 clean,disc clean
Model,,,,,,,,
gpt-4o,165,56/165 = 33.9%,41/165 = 24.8%,24/9,147,48/147 = 32.7%,39/147 = 26.5%,18/9
gpt-5.4-mini,165,53/165 = 32.1%,55/165 = 33.3%,17/19,153,47/153 = 30.7%,50/153 = 32.7%,14/17
Qwen3.5-9B,165,79/165 = 47.9%,79/165 = 47.9%,24/24,141,67/141 = 47.5%,69/141 = 48.9%,19/21
Qwen3.7-Plus,164,109/164 = 66.5%,101/164 = 61.6%,21/13,143,92/143 = 64.3%,87/143 = 60.8%,14/9

There are some partial results on how gpt-4o performs with the leak filter on which I did to capture variance but I guess those are now results for the switched on leak filter.

In [23]:
# Reuses BASELINE_DIR, leak_step (cell above), pickle, pd and display from the cells above.
import statistics

GPT4O_RUNS = {
    # The one the tables above use: leak filter OFF, search at 1.0 q/s.
    "filter OFF (ref)": BASELINE_DIR / "naive_react_gpt-4o_False_fixedbrowser",
    "filter ON #1": BASELINE_DIR / "naive_react_gpt-4o_False_var1",
    "filter ON #2": BASELINE_DIR / "naive_react_gpt-4o_False_var2",
    "filter ON #3": BASELINE_DIR / "naive_react_gpt-4o_False_var3",
}

var_rows, var_acc, var_tok = [], [], []
for label, pkl_dir in GPT4O_RUNS.items():
    if not pkl_dir.exists():
        continue
    rows = []
    for p in sorted(pkl_dir.glob("*.pkl"), key=lambda q: int(q.stem)):
        with open(p, "rb") as f:
            rows.append(pickle.load(f))
    n = len(rows)
    correct = sum(1 for r in rows if r.get("is_correct"))
    tokens = [r["token_counts"]["total_tokens"] for r in rows]
    if label.startswith("filter ON"):
        var_acc.append(correct / n)
        var_tok.append(sum(tokens) / n)
    var_rows.append({
        "Run": label,
        "Questions": n,
        "Errors": sum(1 for r in rows if r.get("error")),
        "Accuracy": f"{correct}/{n} = {correct / n:.1%}",
        "Steps": f"{sum(r.get('num_steps', 0) for r in rows) / n:.1f}",
        "Mean tokens": f"{sum(tokens) / n:,.0f}",
        "Median tokens": f"{statistics.median(tokens):,.0f}",
        # Zero here is the filter working; the reference run predates it.
        "Leak-flagged": sum(1 for r in rows if leak_step(r)),
    })

print("=== naive gpt-4o, three repeats with the leak filter ON (search 0.15 q/s) ===")
display(pd.DataFrame(var_rows).set_index("Run"))
if len(var_acc) > 1:
    print(f"filter-ON accuracy: mean {statistics.mean(var_acc):.1%}, "
          f"sd {statistics.stdev(var_acc):.1%}, range {min(var_acc):.1%}-{max(var_acc):.1%}")
    print(f"filter-ON mean tokens: {statistics.mean(var_tok):,.0f} "
          f"(sd {statistics.stdev(var_tok):,.0f})")

=== naive gpt-4o, three repeats with the leak filter ON (search 0.15 q/s) ===

,Questions,Errors,Accuracy,Steps,Mean tokens,Median tokens,Leak-flagged
Run,,,,,,,
filter OFF (ref),165,0,56/165 = 33.9%,8.2,"76,848","30,242",14
filter ON #1,165,0,39/165 = 23.6%,11.8,"142,828","37,716",0
filter ON #2,165,1,46/165 = 27.9%,10.9,"127,841","41,840",0
filter ON #3,165,0,39/165 = 23.6%,10.6,"125,982","41,008",0

filter-ON accuracy: mean 25.1%, sd 2.4%, range 23.6%-27.9%
filter-ON mean tokens: 132,217 (sd 9,236)

I guess above numbers show that having a filter to avoid leaking answers can drastically change performance, so we might have to run n=1 program again. But before that let's see if we can get probabilities out. So what I would like is as follows:

```python
system_prompt = …
task = …
is_final = False
memory = task + system_prompt
while not is_final:
    # Sample an action specification from the language model
    thought, action_spec = sample(LLM(.. | memory))
    # Sample n actions using the action specification
    fill_in, probs = sample(LLM(.. | memory + thought + action_spec + "fill in the specification"), n)
    actions = action_spec[fill_in]
    results = execute(actions)
    # Use LLM-as-a-judge to pick which step makes the most progress
    feedback, likelihoods = sample(LLM(.. | task + thought + actions + results + "Look at these {n} pairs of thought action and results and rank them"))
    final_thought, final_action_spec, final_fill_in, final_result = select(feedback, thought, action_spec, fill_in, results, probs, likelihoods)
	is_final = check(final_action_spec)
	if is_final:
		answer = extract_answer(action)
	else:
		memory += final_thought + final_action_spec + final_fill_in + final_result
return answer
```

Essentially I would like to do the following two things:
1. Get log probs corresponding to each fill_in
    a. This is just a change in the arguments being sent to API call and handling the output.
2. Change the judge to say which number gives the best answer, and use the logprobs of the number as likelihood.
    a. This requires writing a separate function that configures judge like that and gets the number's likelihood

This [jupyter notebook](baseline/traceletReAct_trajectory.ipynb) shows traces with probabilities.

In the above notebook, if one looks carefully at the trajectories, you can get different token probabilities for the same generation. This can happen due to multiple reasons:
1. Floating point errors
2. Models being non-deterministic
Apparently, this phenomenon is documented here: https://github.com/vllm-project/vllm/issues/7779 
There is also a notebook to see the effect here: [logprob_nondeterminism](baseline/logprob_nondeterminism.ipynb)

Now before I go further tinkering around with probabilities etc., I am going to try putting down results for naiveReAct, n=1, n=3 and n=5 together, first the accuracies and then the token counts.

In [24]:
# Reuses BASELINE_DIR, contiguous_prefix, pickle, pd and display from the cells above.

ARM_DIRS = {
    "naive": {
        "gpt-4o": BASELINE_DIR / "naive_react_gpt-4o_False_fixedbrowser",
        "gpt-5.4-mini": BASELINE_DIR / "naive_react_gpt-5.4-mini_False_fixedbrowser",
        "Qwen3.5-9B": BASELINE_DIR / "naive_react_Qwen" / "Qwen3.5-9B_False_fixedbrowser",
        "Qwen3.7-Plus": BASELINE_DIR / "naive_react_Qwen" / "Qwen3.7-Plus_False_fixedbrowser",
    },
    "n=1": {
        "gpt-4o": BASELINE_DIR / "tracelet_direct_n1_tp_v5_react_gpt-4o",
        "gpt-5.4-mini": BASELINE_DIR / "tracelet_direct_n1_tp_v5_react_gpt-5.4-mini",
        "Qwen3.5-9B": BASELINE_DIR / "tracelet_direct_n1_tp_v5_react_Qwen" / "Qwen3.5-9B",
        "Qwen3.7-Plus": BASELINE_DIR / "tracelet_direct_n1_tp_v5_react_Qwen" / "Qwen3.7-Plus",
    },
    "n=3": {
        "gpt-4o": BASELINE_DIR / "tracelet_direct_tp_v6n3_react_gpt-4o",
        "gpt-5.4-mini": BASELINE_DIR / "tracelet_direct_tp_v6n3_react_gpt-5.4-mini",
        "Qwen3.5-9B": BASELINE_DIR / "tracelet_direct_tp_v6n3_react_Qwen" / "Qwen3.5-9B",
        "Qwen3.7-Plus": BASELINE_DIR / "tracelet_direct_tp_v5n3_react_Qwen" / "Qwen3.7-Plus",
    },
    "n=5": {
        "gpt-4o": BASELINE_DIR / "tracelet_direct_n5_tp_v6n5_react_gpt-4o",
        "gpt-5.4-mini": BASELINE_DIR / "tracelet_direct_n5_tp_v6n5_react_gpt-5.4-mini",
        "Qwen3.5-9B": BASELINE_DIR / "tracelet_direct_n5_tp_v6n5_react_Qwen" / "Qwen3.5-9B",
        # Qwen3.7-Plus is absent by necessity: the provider rejects n=5 ("Range of n should be [1, 4]").
    },
}
MODELS = ["gpt-4o", "gpt-5.4-mini", "Qwen3.5-9B", "Qwen3.7-Plus"]
ARMS = list(ARM_DIRS)

# Answer-key leak filter status per arm, from baseline/RUNS.md. naive and n=1 predate the filter
# (added 2026-09-02); n=3 and n=5 ran with it on. This is a confound, not a footnote -- see below.
ARM_FILTER = {"naive": "off", "n=1": "off", "n=3": "ON", "n=5": "ON"}
ARM_RPS = {"naive": "1.0", "n=1": "1.0", "n=3": "0.15", "n=5": "0.2-0.3"}
LABEL = {arm: f"{arm} [filter {ARM_FILTER[arm]}]" for arm in ARMS}

# gpt-4o is the only model with naive repeats under the filter, so it is the only like-for-like
# baseline available for the filtered arms.
NAIVE_FILTER_ON = {
    "gpt-4o": [
        BASELINE_DIR / "naive_react_gpt-4o_False_var1",
        BASELINE_DIR / "naive_react_gpt-4o_False_var2",
        BASELINE_DIR / "naive_react_gpt-4o_False_var3",
    ]
}


def arm_rows(pkl_dir, n: int) -> list[dict]:
    rows = []
    for i in range(n):
        with open(pkl_dir / f"{i}.pkl", "rb") as f:
            rows.append(pickle.load(f))
    return rows


# Every arm of a model is scored on the same questions: the shortest contiguous prefix any of
# its arms has finished. Without this a still-running sweep would be compared on an easier subset.
paired_n = {}
for model in MODELS:
    lengths = [contiguous_prefix(d[model]) for d in ARM_DIRS.values() if model in d and d[model].exists()]
    paired_n[model] = min(lengths) if lengths else 0

acc_rows, tok_rows, step_rows = [], [], []
for model in MODELS:
    n = paired_n[model]
    acc = {"Model": model, "Questions": n}
    steps = {"Model": model, "Questions": n}
    for arm in ARMS:
        pkl_dir = ARM_DIRS[arm].get(model)
        if n == 0 or pkl_dir is None or not pkl_dir.exists():
            acc[LABEL[arm]] = steps[LABEL[arm]] = "n/a"
            continue
        rows = arm_rows(pkl_dir, n)
        correct = sum(1 for r in rows if r.get("is_correct"))
        errors = sum(1 for r in rows if r.get("error"))
        # An errored question scores as incorrect, so surface the count rather than hiding it.
        acc[LABEL[arm]] = f"{correct}/{n} = {correct / n:.1%}" + (f" ({errors}e)" if errors else "")

        # A run that hits MAX_STEPS=50 was truncated, not finished, so flag those separately.
        counts = [r.get("num_steps", 0) for r in rows]
        capped = sum(1 for c in counts if c >= 51)
        steps[LABEL[arm]] = f"{sum(counts) / n:.1f}" + (f" ({capped} capped)" if capped else "")

        tokens = [r["token_counts"] for r in rows]
        tok_rows.append({
            "Model": model,
            "Arm": LABEL[arm],
            "Questions": n,
            "Input / q": sum(c["input_tokens"] for c in tokens) / n,
            "Output / q": sum(c["output_tokens"] for c in tokens) / n,
            "Total / q": sum(c["total_tokens"] for c in tokens) / n,
            "Total (all q)": sum(c["total_tokens"] for c in tokens),
        })
    acc_rows.append(acc)
    step_rows.append(steps)

acc_table = pd.DataFrame(acc_rows).set_index("Model")
print("=== Accuracy: naiveReAct vs tracelet n=1 / n=3 / n=5 ===")
print("Each model's arms are scored on the same question prefix; '(Ne)' counts errored questions,")
print("which score as incorrect. Qwen3.7-Plus has no n=5 arm -- the provider caps n at 4.")
print()
print("!! CONFOUND: naive and n=1 ran BEFORE the answer-key leak filter existed, n=3 and n=5 with")
print("   it on. An unfiltered run can read GAIA answer keys straight out of search snippets, so")
print("   the naive and n=1 columns are inflated. Do not read across the filter boundary.")
display(acc_table)

tok_table = pd.DataFrame(tok_rows)
# Ratio against that model's naive arm, since absolute token counts differ ~10x across models.
naive_total = {r["Model"]: r["Total / q"] for r in tok_rows if r["Arm"] == LABEL["naive"]}
tok_table["vs naive"] = [f"{r['Total / q'] / naive_total[r['Model']]:.2f}x" for _, r in tok_table.iterrows()]
tok_display = tok_table.set_index(["Model", "Arm"])
for col in ("Input / q", "Output / q", "Total / q", "Total (all q)"):
    tok_display[col] = tok_display[col].map(lambda v: f"{v:,.0f}")
print("\n=== Token counts ===")
print("Per-question means, plus each arm's summed total. Note input dominates: memory is resent")
print("in full on every LLM call, so input grows with trajectory length.")
display(tok_display)

step_table = pd.DataFrame(step_rows).set_index("Model")
print("\n=== Average steps per question ===")
print("'(N capped)' counts trajectories that hit MAX_STEPS=50 and were truncated rather than")
print("finishing. Steps track failure more than effort: a correct answer takes fewer of them.")
display(step_table)


# The filter boundary quantified, on the one model where naive was repeated under the filter.
if NAIVE_FILTER_ON:
    ref_rows = []
    for model, dirs in NAIVE_FILTER_ON.items():
        n = paired_n[model]
        for label, pkl_dir in [("naive [filter off]", ARM_DIRS["naive"][model])] + [
            (f"naive [filter ON] #{i}", d) for i, d in enumerate(dirs, start=1)
        ]:
            if not pkl_dir.exists():
                continue
            rows = arm_rows(pkl_dir, n)
            correct = sum(1 for r in rows if r.get("is_correct"))
            ref_rows.append({
                "Model": model,
                "Run": label,
                "Accuracy": f"{correct}/{n} = {correct / n:.1%}",
                "acc": correct / n,
                "Steps": f"{sum(r.get('num_steps', 0) for r in rows) / n:.1f}",
                "Total / q": f"{sum(r['token_counts']['total_tokens'] for r in rows) / n:,.0f}",
            })
    ref = pd.DataFrame(ref_rows)
    on = [r["acc"] for r in ref_rows if "ON" in r["Run"]]
    off = next(r["acc"] for r in ref_rows if "off" in r["Run"])
    print("\n=== The filter boundary, quantified (gpt-4o only) ===")
    print("Turning the filter on costs naive gpt-4o "
          f"{off - sum(on) / len(on):.1%} ({off:.1%} -> {sum(on) / len(on):.1%} mean of "
          f"{len(on)} repeats, range {min(on):.1%}-{max(on):.1%}).")
    print("That is ~3x the +-2.4pp noise floor, and it is larger than any arm-to-arm difference in")
    print("the first table. Against the filter-ON naive baseline the filtered arms look BETTER,")
    print("not worse -- so the apparent naive win for gpt-4o is a leakage artefact.")
    display(ref.drop(columns="acc").set_index(["Model", "Run"]))

=== Accuracy: naiveReAct vs tracelet n=1 / n=3 / n=5 ===
Each model's arms are scored on the same question prefix; '(Ne)' counts errored questions,
which score as incorrect. Qwen3.7-Plus has no n=5 arm -- the provider caps n at 4.

!! CONFOUND: naive and n=1 ran BEFORE the answer-key leak filter existed, n=3 and n=5 with
   it on. An unfiltered run can read GAIA answer keys straight out of search snippets, so
   the naive and n=1 columns are inflated. Do not read across the filter boundary.

,Questions,naive [filter off],n=1 [filter off],n=3 [filter ON],n=5 [filter ON]
Model,,,,,
gpt-4o,165,56/165 = 33.9%,41/165 = 24.8%,46/165 = 27.9%,55/165 = 33.3%
gpt-5.4-mini,165,53/165 = 32.1%,55/165 = 33.3%,58/165 = 35.2%,58/165 = 35.2%
Qwen3.5-9B,165,79/165 = 47.9%,79/165 = 47.9%,79/165 = 47.9%,79/165 = 47.9% (1e)
Qwen3.7-Plus,165,109/165 = 66.1% (1e),101/165 = 61.2%,105/165 = 63.6% (1e),n/a

=== Token counts ===
Per-question means, plus each arm's summed total. Note input dominates: memory is resent
in full on every LLM call, so input grows with trajectory length.

                                 Questions Input / q Output / q Total / q  \
Model        Arm
gpt-4o       naive [filter off]        165    75,587      1,261    76,848
             n=1 [filter off]          165   318,004      1,786   319,790
             n=3 [filter ON]           165   243,306      1,894   245,200
             n=5 [filter ON]           165   265,426      2,544   267,970
gpt-5.4-mini naive [filter off]        165    26,263        444    26,707
             n=1 [filter off]          165   166,049      1,067   167,116
             n=3 [filter ON]           165   200,328      1,473   201,801
             n=5 [filter ON]           165   155,234      1,571   156,805
Qwen3.5-9B   naive [filter off]        165   368,808      3,808   372,615
             n=1 [filter off]          165   614,792      5,973   620,765
             n=3 [filter ON]           165   630,187      6,859   637,046
             n=5 [filter ON]           165   592,873      8,834   601,707
Qwen3.7-Plus naive [filter off]        165   317,807      2,988   320,795
             n=1 [filter off]          165   708,836      3,700   712,536
             n=3 [filter ON]           165   481,814      3,513   485,327

                                Total (all q) vs naive
Model        Arm
gpt-4o       naive [filter off]    12,679,920    1.00x
             n=1 [filter off]      52,765,417    4.16x
             n=3 [filter ON]       40,458,066    3.19x
             n=5 [filter ON]       44,214,987    3.49x
gpt-5.4-mini naive [filter off]     4,406,637    1.00x
             n=1 [filter off]      27,574,138    6.26x
             n=3 [filter ON]       33,297,103    7.56x
             n=5 [filter ON]       25,872,848    5.87x
Qwen3.5-9B   naive [filter off]    61,481,541    1.00x
             n=1 [filter off]     102,426,228    1.67x
             n=3 [filter ON]      105,112,672    1.71x
             n=5 [filter ON]       99,281,588    1.61x
Qwen3.7-Plus naive [filter off]    52,931,141    1.00x
             n=1 [filter off]     117,568,500    2.22x
             n=3 [filter ON]       80,078,952    1.51x

=== Average steps per question ===
'(N capped)' counts trajectories that hit MAX_STEPS=50 and were truncated rather than
finishing. Steps track failure more than effort: a correct answer takes fewer of them.

,Questions,naive [filter off],n=1 [filter off],n=3 [filter ON],n=5 [filter ON]
Model,,,,,
gpt-4o,165,8.2 (5 capped),12.3 (8 capped),9.8 (5 capped),9.9 (8 capped)
gpt-5.4-mini,165,5.0 (1 capped),7.7 (1 capped),7.5 (2 capped),6.4 (1 capped)
Qwen3.5-9B,165,17.0 (15 capped),18.1 (16 capped),17.3 (20 capped),16.9 (16 capped)
Qwen3.7-Plus,165,16.1 (10 capped),17.1 (17 capped),17.4 (13 capped),n/a

=== The filter boundary, quantified (gpt-4o only) ===
Turning the filter on costs naive gpt-4o 8.9% (33.9% -> 25.1% mean of 3 repeats, range 23.6%-27.9%).
That is ~3x the +-2.4pp noise floor, and it is larger than any arm-to-arm difference in
the first table. Against the filter-ON naive baseline the filtered arms look BETTER,
not worse -- so the apparent naive win for gpt-4o is a leakage artefact.

                                   Accuracy Steps Total / q
Model  Run
gpt-4o naive [filter off]    56/165 = 33.9%   8.2    76,848
       naive [filter ON] #1  39/165 = 23.6%  11.8   142,828
       naive [filter ON] #2  46/165 = 27.9%  10.9   127,841
       naive [filter ON] #3  39/165 = 23.6%  10.6   125,982

The above numbers are not comparable due to leak filter being off for some of the runs. After running those experiments with leak filter on, below are the results.

In [25]:
# Same as the cell above, but every arm now ran with the leak filter ON -- no boundary to
# track this time. Reuses BASELINE_DIR, contiguous_prefix, pickle, pd and display.

ARM_DIRS = {
    "naive": {
        # gpt-4o has no single filter-on naive dir -- it predates that convention and instead
        # has three repeats (var1/var2/var3, see the filter-boundary cell above); var2 is used
        # here for one consistent paired comparison, not averaged across the three.
        "gpt-4o": BASELINE_DIR / "naive_react_gpt-4o_False_var2",
        "gpt-5.4-mini": BASELINE_DIR / "naive_react_gpt-5.4-mini_False_filteron",
        "Qwen3.5-9B": BASELINE_DIR / "naive_react_Qwen" / "Qwen3.5-9B_False_filteron",
        "Qwen3.7-Plus": BASELINE_DIR / "naive_react_Qwen" / "Qwen3.7-Plus_False_filteron",
    },
    "n=1": {
        "gpt-4o": BASELINE_DIR / "tracelet_direct_n1_tp_v7_react_gpt-4o",
        "gpt-5.4-mini": BASELINE_DIR / "tracelet_direct_n1_tp_v7_react_gpt-5.4-mini",
        "Qwen3.5-9B": BASELINE_DIR / "tracelet_direct_n1_tp_v7_react_Qwen" / "Qwen3.5-9B",
        "Qwen3.7-Plus": BASELINE_DIR / "tracelet_direct_n1_tp_v7_react_Qwen" / "Qwen3.7-Plus",
    },
    "n=3": {
        "gpt-4o": BASELINE_DIR / "tracelet_direct_tp_v6n3_react_gpt-4o",
        "gpt-5.4-mini": BASELINE_DIR / "tracelet_direct_tp_v6n3_react_gpt-5.4-mini",
        "Qwen3.5-9B": BASELINE_DIR / "tracelet_direct_tp_v6n3_react_Qwen" / "Qwen3.5-9B",
        "Qwen3.7-Plus": BASELINE_DIR / "tracelet_direct_tp_v5n3_react_Qwen" / "Qwen3.7-Plus",
    },
    "n=5": {
        "gpt-4o": BASELINE_DIR / "tracelet_direct_n5_tp_v6n5_react_gpt-4o",
        "gpt-5.4-mini": BASELINE_DIR / "tracelet_direct_n5_tp_v6n5_react_gpt-5.4-mini",
        "Qwen3.5-9B": BASELINE_DIR / "tracelet_direct_n5_tp_v6n5_react_Qwen" / "Qwen3.5-9B",
        # Qwen3.7-Plus is absent by necessity: the provider rejects n=5 ("Range of n should be [1, 4]").
    },
}
MODELS = ["gpt-4o", "gpt-5.4-mini", "Qwen3.5-9B", "Qwen3.7-Plus"]
ARMS = list(ARM_DIRS)


def arm_rows(pkl_dir, n: int) -> list[dict]:
    rows = []
    for i in range(n):
        with open(pkl_dir / f"{i}.pkl", "rb") as f:
            rows.append(pickle.load(f))
    return rows


# Every arm of a model is scored on the same questions: the shortest contiguous prefix any of
# its arms has finished. Qwen3.5-9B's n=1 filter-on sweep is still running, so its row is partial.
paired_n = {}
for model in MODELS:
    lengths = [contiguous_prefix(d[model]) for d in ARM_DIRS.values() if model in d and d[model].exists()]
    paired_n[model] = min(lengths) if lengths else 0

acc_rows, tok_rows, step_rows = [], [], []
for model in MODELS:
    n = paired_n[model]
    acc = {"Model": model, "Questions": n}
    steps = {"Model": model, "Questions": n}
    for arm in ARMS:
        pkl_dir = ARM_DIRS[arm].get(model)
        if n == 0 or pkl_dir is None or not pkl_dir.exists():
            acc[arm] = steps[arm] = "n/a"
            continue
        rows = arm_rows(pkl_dir, n)
        correct = sum(1 for r in rows if r.get("is_correct"))
        errors = sum(1 for r in rows if r.get("error"))
        # An errored question scores as incorrect, so surface the count rather than hiding it.
        acc[arm] = f"{correct}/{n} = {correct / n:.1%}" + (f" ({errors}e)" if errors else "")

        # A run that hits MAX_STEPS=50 was truncated, not finished, so flag those separately.
        counts = [r.get("num_steps", 0) for r in rows]
        capped = sum(1 for c in counts if c >= 51)
        steps[arm] = f"{sum(counts) / n:.1f}" + (f" ({capped} capped)" if capped else "")

        tokens = [r["token_counts"] for r in rows]
        tok_rows.append({
            "Model": model,
            "Arm": arm,
            "Questions": n,
            "Input / q": sum(c["input_tokens"] for c in tokens) / n,
            "Output / q": sum(c["output_tokens"] for c in tokens) / n,
            "Total / q": sum(c["total_tokens"] for c in tokens) / n,
            "Total (all q)": sum(c["total_tokens"] for c in tokens),
        })
    acc_rows.append(acc)
    step_rows.append(steps)

acc_table = pd.DataFrame(acc_rows).set_index("Model")
print("=== Accuracy: naiveReAct vs tracelet n=1 / n=3 / n=5 -- ALL ARMS, LEAK FILTER ON ===")
print("Each model's arms are scored on the same question prefix; '(Ne)' counts errored questions,")
print("which score as incorrect. Qwen3.7-Plus has no n=5 arm -- the provider caps n at 4.")
print("Qwen3.5-9B's n=1 sweep is still running, so its row is a partial prefix, not the full 165.")
display(acc_table)

tok_table = pd.DataFrame(tok_rows)
naive_total = {r["Model"]: r["Total / q"] for r in tok_rows if r["Arm"] == "naive"}
tok_table["vs naive"] = [f"{r['Total / q'] / naive_total[r['Model']]:.2f}x" for _, r in tok_table.iterrows()]
tok_display = tok_table.set_index(["Model", "Arm"])
for col in ("Input / q", "Output / q", "Total / q", "Total (all q)"):
    tok_display[col] = tok_display[col].map(lambda v: f"{v:,.0f}")
print("\n=== Token counts ===")
print("Per-question means, plus each arm's summed total. Note input dominates: memory is resent")
print("in full on every LLM call, so input grows with trajectory length.")
display(tok_display)

step_table = pd.DataFrame(step_rows).set_index("Model")
print("\n=== Average steps per question ===")
print("'(N capped)' counts trajectories that hit MAX_STEPS=50 and were truncated rather than")
print("finishing. Steps track failure more than effort: a correct answer takes fewer of them.")
display(step_table)

=== Accuracy: naiveReAct vs tracelet n=1 / n=3 / n=5 -- ALL ARMS, LEAK FILTER ON ===
Each model's arms are scored on the same question prefix; '(Ne)' counts errored questions,
which score as incorrect. Qwen3.7-Plus has no n=5 arm -- the provider caps n at 4.
Qwen3.5-9B's n=1 sweep is still running, so its row is a partial prefix, not the full 165.

,Questions,naive,n=1,n=3,n=5
Model,,,,,
gpt-4o,165,46/165 = 27.9% (1e),48/165 = 29.1%,46/165 = 27.9%,55/165 = 33.3%
gpt-5.4-mini,165,50/165 = 30.3%,67/165 = 40.6%,58/165 = 35.2%,58/165 = 35.2%
Qwen3.5-9B,165,86/165 = 52.1%,67/165 = 40.6%,79/165 = 47.9%,79/165 = 47.9% (1e)
Qwen3.7-Plus,165,94/165 = 57.0% (3e),100/165 = 60.6% (1e),105/165 = 63.6% (1e),n/a

=== Token counts ===
Per-question means, plus each arm's summed total. Note input dominates: memory is resent
in full on every LLM call, so input grows with trajectory length.

                    Questions Input / q Output / q Total / q Total (all q)  \
Model        Arm
gpt-4o       naive        165   126,206      1,634   127,841    21,093,688
             n=1          165   252,778      1,591   254,370    41,971,015
             n=3          165   243,306      1,894   245,200    40,458,066
             n=5          165   265,426      2,544   267,970    44,214,987
gpt-5.4-mini naive        165    28,293        473    28,767     4,746,525
             n=1          165   158,983        888   159,871    26,378,754
             n=3          165   200,328      1,473   201,801    33,297,103
             n=5          165   155,234      1,571   156,805    25,872,848
Qwen3.5-9B   naive        165   459,829      4,079   463,908    76,544,841
             n=1          165   671,885      5,899   677,784   111,834,364
             n=3          165   630,187      6,859   637,046   105,112,672
             n=5          165   592,873      8,834   601,707    99,281,588
Qwen3.7-Plus naive        165   419,404      3,246   422,651    69,737,370
             n=1          165   781,777      3,986   785,763   129,650,847
             n=3          165   481,814      3,513   485,327    80,078,952

                   vs naive
Model        Arm
gpt-4o       naive    1.00x
             n=1      1.99x
             n=3      1.92x
             n=5      2.10x
gpt-5.4-mini naive    1.00x
             n=1      5.56x
             n=3      7.02x
             n=5      5.45x
Qwen3.5-9B   naive    1.00x
             n=1      1.46x
             n=3      1.37x
             n=5      1.30x
Qwen3.7-Plus naive    1.00x
             n=1      1.86x
             n=3      1.15x

=== Average steps per question ===
'(N capped)' counts trajectories that hit MAX_STEPS=50 and were truncated rather than
finishing. Steps track failure more than effort: a correct answer takes fewer of them.

,Questions,naive,n=1,n=3,n=5
Model,,,,,
gpt-4o,165,10.9 (9 capped),9.5 (6 capped),9.8 (5 capped),9.9 (8 capped)
gpt-5.4-mini,165,5.1,6.6 (1 capped),7.5 (2 capped),6.4 (1 capped)
Qwen3.5-9B,165,20.2 (20 capped),20.6 (27 capped),17.3 (20 capped),16.9 (16 capped)
Qwen3.7-Plus,165,19.0 (19 capped),18.1 (16 capped),17.4 (13 capped),n/a

Ok, so now that we have a new way of doing ReAct, let's examine it algorithmically and see what's happening.

```python
system_prompt = …
task = …
is_final = False
memory = task + system_prompt
while not is_final:
    thought, action_spec = sample(LLM(.. | memory))

    # The prior distribution over the possible arguments 
    fill_in, probs = LLM(.. | memory + thought + action_spec + "fill in the specification")
    actions = action_spec[fill_in]
    results = execute(actions)
    
    # The likelihood distribution
    feedback, likelihoods = LLM(.. | task + thought + actions + results + "Look at these {n} pairs of thought action and results and rank them")

    # Compute the MAP (Maximuma-a-posteriori)
    final_thought, final_action_spec, final_fill_in, final_result = select(feedback, thought, action_spec, fill_in, results, probs, likelihoods)
	
    is_final = check(final_action_spec)
	if is_final:
		answer = extract_answer(action)
	else:
		memory += final_thought + final_action_spec + final_fill_in + final_result
return answer
```

Note that in the above description of ReAct, we have a mini probabilistic inference running at every iteration of the loop. We get the prior distribution $P_{\text{prior}}$ over all arguments in the action template and a $P_{\text{likelihood}}$ over the arguments as well. These two distributions can further be used in Bayesian inference in accordance to the following equation.

$$P_{\text{posterior}}(\text{arg}) \propto P_{prior}(\text{arg}) \cdot P_{\text{likelihood}}(\text{arg})$$

And finally arguments are picked as the MAP of the posterior distribution.

$$arg' = \argmax_{a} P_{\text{posterior}}(\text{a})$$

thought, action_spec =...
fill_in = LLM(. | thought, action_spec).  ## prior

results = execute(action_spec, fill_in)
final_score = LLM(. | results, "score them")

final_fill_in = argmax_(fill_in) final_score 


$P_{\text{posterior}}(fill_in | good(results)) = P_{\text{prior}}(fill_in) P_{\text{likelihood}}( good(results) | fill_in)  / P(good(results))$

$P_{\text{posterior}}(observation being good | arg)$
Prior -> Language model's prior belief on what argument to go for
Likelihood -> Judge looks at the observations (execution results) 

Is judge weird? probably not, we do not have enough diverse samples so which is the problem
    - maybe implement beam search
Let's get beam search going with 5 different trajectories

Beam Search 10 parallel, choose 5
Real Trajectories
Measure pass@k, accuracies
Diversity would bite
Beam Search output to probabilistic programs

TODOs:
1. Poorva: Simple sketch of how programs look
        Generating independent (thought, action, results)
        Judge to get best k out of n
        Syntax of how I want to express the output of the beam search
2. Kyle: Implement the simple sketch of probabilistic programs



Verbalized logits for fill_in, likelihood, and combine them

Currently in the implementation, we do not get the maximum-a-posteriori estimate, we get the maximum likelihood estimate, which we report below.

In [28]:
display(acc_table)

,Questions,naive,n=1,n=3,n=5
Model,,,,,
gpt-4o,165,46/165 = 27.9% (1e),48/165 = 29.1%,46/165 = 27.9%,55/165 = 33.3%
gpt-5.4-mini,165,50/165 = 30.3%,67/165 = 40.6%,58/165 = 35.2%,58/165 = 35.2%
Qwen3.5-9B,165,86/165 = 52.1%,67/165 = 40.6%,79/165 = 47.9%,79/165 = 47.9% (1e)
Qwen3.7-Plus,165,94/165 = 57.0% (3e),100/165 = 60.6% (1e),105/165 = 63.6% (1e),n/a

And as one can see in the table above, there is not a very clear trend if choosing MLE argument at each step helps with accuracy, the trend from n=1 to n=3 to n=5 is not non-decreasing as one would expect to be. (CAVEAT: These are single runs).

As an explanation for this, we investigate various choices of distributions available for different components.

### Quantity to be maximized

The results probably depend a lot on what quantity are we trying to maximize, the likelihood $P_{\text{likelihood}}$ or the posterior $P_{\text{prior}}P_{\text{likelihood}}$. 

It is well known in the RL literature and reward hacking literature that since likelihood comes from imperfect judge, maximizing likelihood can lead to sub-optimal behaviour. Not sure if that holds in the following context. But it is worth noting the results of this experiment where likelihood is replaced by a uniform distribution, i.e. the continuing path is selected uniformly at random.

In [31]:
# Reuses BASELINE_DIR, contiguous_prefix, mcnemar, pickle, pd and display from the cells above.

JUDGE_DIRS = {
    "gpt-4o": BASELINE_DIR / "tracelet_direct_n5_tp_v6n5_react_gpt-4o",
    "gpt-5.4-mini": BASELINE_DIR / "tracelet_direct_n5_tp_v6n5_react_gpt-5.4-mini",
    "Qwen3.5-9B": BASELINE_DIR / "tracelet_direct_n5_tp_v6n5_react_Qwen" / "Qwen3.5-9B",
    # Qwen3.7-Plus has no n=5 arm at all -- the provider caps n at 4.
}
RANDOM_DIRS = {
    "gpt-4o": BASELINE_DIR / "tracelet_direct_n5_tp_rand5_react_gpt-4o",
    "gpt-5.4-mini": BASELINE_DIR / "tracelet_direct_n5_tp_rand5_react_gpt-5.4-mini",
    "Qwen3.5-9B": BASELINE_DIR / "tracelet_direct_n5_tp_rand5_react_Qwen" / "Qwen3.5-9B",
}


def load_rows(pkl_dir, n):
    rows = []
    for i in range(n):
        with open(pkl_dir / f"{i}.pkl", "rb") as f:
            rows.append(pickle.load(f))
    return rows


comparison_rows = []
for model in JUDGE_DIRS:
    judge_dir, random_dir = JUDGE_DIRS[model], RANDOM_DIRS[model]
    n = min(contiguous_prefix(judge_dir), contiguous_prefix(random_dir))
    judge_rows, random_rows = load_rows(judge_dir, n), load_rows(random_dir, n)
    judge_correct = [bool(r.get("is_correct")) for r in judge_rows]
    random_correct = [bool(r.get("is_correct")) for r in random_rows]
    j_only, r_only, p = mcnemar(judge_correct, random_correct)
    j_tok = sum(r["token_counts"]["total_tokens"] for r in judge_rows) / n
    r_tok = sum(r["token_counts"]["total_tokens"] for r in random_rows) / n
    j_steps = sum(r["num_steps"] for r in judge_rows) / n
    r_steps = sum(r["num_steps"] for r in random_rows) / n
    comparison_rows.append({
        "Model": model,
        "Questions": n,
        "Judge accuracy": f"{sum(judge_correct)}/{n} = {sum(judge_correct) / n:.1%}",
        "Random accuracy": f"{sum(random_correct)}/{n} = {sum(random_correct) / n:.1%}",
        # "Discordant (judge/random)": f"{j_only}/{r_only}",
        # "McNemar p": f"{p:.3f}",
        "Judge tokens/q": f"{j_tok:,.0f}",
        "Random tokens/q": f"{r_tok:,.0f}",
        "Judge steps/q": f"{j_steps:.2f}",
        "Random steps/q": f"{r_steps:.2f}",
    })

print("=== Judge selection vs random selection, n=5 (control experiment) ===")
print("Qwen3.7-Plus excluded -- the provider caps n at 4 and refuses n>1 with logprobs, so it")
print("never had an n=5 arm to compare against.")
display(pd.DataFrame(comparison_rows).set_index("Model"))

=== Judge selection vs random selection, n=5 (control experiment) ===
Qwen3.7-Plus excluded -- the provider caps n at 4 and refuses n>1 with logprobs, so it
never had an n=5 arm to compare against.

,Questions,Judge accuracy,Random accuracy,Judge tokens/q,Random tokens/q,Judge steps/q,Random steps/q
Model,,,,,,,
gpt-4o,165,55/165 = 33.3%,40/165 = 24.2%,"267,970","274,973",9.85,12.36
gpt-5.4-mini,165,58/165 = 35.2%,63/165 = 38.2%,"156,805","179,450",6.41,8.16
Qwen3.5-9B,165,79/165 = 47.9%,80/165 = 48.5%,"601,707","607,643",16.88,18.35

Another interesting thing to see above is the fact that not only accuracies are comparable by random also uses more tokens than LLM as a judge due to more steps even when the judge call was eliminated for random.

So, the natural next question becomes if maximizing the posterior makes more sense, that opens up a lot of questions such as what prior and what likelihood should be used since the choices can change the mode of their product accordingly. So, what are these choices:

$P_{\text{prior}}$: For the prior of the arguments, we can use either of the following choices:
1. Product of the next-token likelihoods $\prod_{i=1}^{n} P(x_i | x_{<i})$
2. Geometric mean of the next-token likelihoods $\sqrt[n]{\prod_{i=1}^{n} P(x_i | x_{<i})}$
3. Normalized form of the either of the above using softmax

$P_{\text{likelihood}}$: For the likelihood of the argument, result pairs, we can use either of the following choices:
1. Normalized judge scores
2. Softmax-normalized judge scores

Based on the description above, we have 9 different ways of selecting the step that continues. 
1. 6 combinations of $P_{\text{prior}} \cdot P_{\text{likelihood}}$
2. $P_{\text{likelihood}}$
3. $P_{\text{prior}}$
4. uniformly at random

We do have the results of comparison between 2 and 4, but I would like to see how often these choices coincide with each other.

Apparently, computing ESS of judge's scores can help to see how effective the judge is. I think this intuition by AI is only coming from the fact that uniform weights give higher ESS whereas peaked weights give lower ESS.

In [32]:
# Reuses BASELINE_DIR, pickle, pd and display from the cells above.

N5_DIRS = {
    "gpt-4o": BASELINE_DIR / "tracelet_direct_n5_tp_v6n5_react_gpt-4o",
    "gpt-5.4-mini": BASELINE_DIR / "tracelet_direct_n5_tp_v6n5_react_gpt-5.4-mini",
    "Qwen3.5-9B": BASELINE_DIR / "tracelet_direct_n5_tp_v6n5_react_Qwen" / "Qwen3.5-9B",
    # Qwen3.7-Plus has no n=5 arm -- the provider caps n at 4 and refuses n>1 with logprobs.
}


def candidate_probs(cands):
    """One selection probability per candidate, matching judge_strategy="scores": clip
    negative scores to 0, then normalize by their sum (uniform if every score is 0)."""
    scores = [c.get("judge_score") for c in cands]
    if any(s is None for s in scores):
        return None
    clipped = [max(0.0, s) for s in scores]
    total = sum(clipped)
    return [s / total for s in clipped] if total > 0 else [1 / len(scores)] * len(scores)


ess_rows = []
for model, pkl_dir in N5_DIRS.items():
    ess_values, essn_values = [], []
    for f in pkl_dir.glob("*.pkl"):
        with open(f, "rb") as fh:
            r = pickle.load(fh)
        for step in r.get("steps", []):
            cands = step.get("candidates") or []
            if len(cands) < 2:
                continue
            probs = candidate_probs(cands)
            if probs is None:
                continue
            ess = 1.0 / sum(p * p for p in probs)
            ess_values.append(ess)
            essn_values.append(ess / len(cands))
    n_steps = len(ess_values)
    ess_rows.append({
        "Model": model,
        "Judged steps": n_steps,
        "Mean ESS": f"{sum(ess_values) / n_steps:.2f}" if n_steps else "n/a",
        "Mean ESS/n": f"{sum(essn_values) / n_steps:.3f}" if n_steps else "n/a",
        "Near-uniform (ESS/n >= 0.95)": f"{sum(1 for v in essn_values if v >= 0.95) / n_steps:.1%}" if n_steps else "n/a",
        "Real discrimination (ESS/n < 0.5)": f"{sum(1 for v in essn_values if v < 0.5) / n_steps:.1%}" if n_steps else "n/a",
    })

print("=== Judge ESS at n=5, per model ===")
print("Qwen3.7-Plus has no n=5 arm -- the provider caps n at 4 and refuses n>1 together with")
print("logprobs, so only 3 of the 4 models can appear here.")
display(pd.DataFrame(ess_rows).set_index("Model"))

=== Judge ESS at n=5, per model ===
Qwen3.7-Plus has no n=5 arm -- the provider caps n at 4 and refuses n>1 together with
logprobs, so only 3 of the 4 models can appear here.

,Judged steps,Mean ESS,Mean ESS/n,Near-uniform (ESS/n >= 0.95),Real discrimination (ESS/n < 0.5)
Model,,,,,
gpt-4o,1216,4.60,0.943,84.5%,4.7%
gpt-5.4-mini,800,4.62,0.925,70.0%,2.8%
Qwen3.5-9B,1424,4.32,0.900,67.1%,5.6%

It is also interesting to see how often prior and likelihoods coincide.

In [33]:
# Reuses BASELINE_DIR, N5_DIRS, pickle, pd and display from the cells above.
from collections import Counter

# Comparing by winning INDEX is misleading: candidates repeat a lot (a step often has the same
# code sampled 2-5 times), so two unrelated rules can "agree" just by both landing on a bigger
# duplicate group. Compare by the actual code TEXT each rule's top choice would run instead, and
# use a chance baseline that accounts for duplication: the probability two independent uniform
# picks land in the same duplicate group, sum((group_size / n) ** 2 for each group).

coincide_rows = []
for model, pkl_dir in N5_DIRS.items():
    total = 0
    agree_text = 0
    chance_sum = 0.0
    for f in pkl_dir.glob("*.pkl"):
        with open(f, "rb") as fh:
            r = pickle.load(fh)
        for step in r.get("steps", []):
            cands = step.get("candidates") or []
            if len(cands) < 2:
                continue
            priors = [c.get("fillin_prob") for c in cands]
            scores = [c.get("judge_score") for c in cands]
            if any(p is None for p in priors) or any(s is None for s in scores):
                continue
            codes = [c.get("code") for c in cands]
            prior_winner = max(range(len(cands)), key=lambda i: priors[i])
            likelihood_winner = max(range(len(cands)), key=lambda i: scores[i])
            total += 1
            agree_text += int(codes[prior_winner] == codes[likelihood_winner])
            n = len(cands)
            chance_sum += sum((g / n) ** 2 for g in Counter(codes).values())
    coincide_rows.append({
        "Model": model,
        "Steps": total,
        "Prior/likelihood pick same code": f"{agree_text}/{total} = {agree_text / total:.1%}" if total else "n/a",
        "Chance baseline (duplicate-aware)": f"{chance_sum / total:.1%}" if total else "n/a",
    })

print("=== How often do P_prior's and P_likelihood's top choices run the same code? ===")
print("Compared by executed code text, not candidate index -- candidates repeat often enough")
print("(most steps have at least one duplicate) that index-based agreement is inflated by shared")
print("duplicate groups rather than genuine correlation between the two signals. The chance")
print("baseline already accounts for that duplication, so a number close to it means no real")
print("correlation between prior and likelihood -- not that the comparison failed.")
display(pd.DataFrame(coincide_rows).set_index("Model"))

=== How often do P_prior's and P_likelihood's top choices run the same code? ===
Compared by executed code text, not candidate index -- candidates repeat often enough
(most steps have at least one duplicate) that index-based agreement is inflated by shared
duplicate groups rather than genuine correlation between the two signals. The chance
baseline already accounts for that duplication, so a number close to it means no real
correlation between prior and likelihood -- not that the comparison failed.

,Steps,Prior/likelihood pick same code,Chance baseline (duplicate-aware)
Model,,,
gpt-4o,1216,804/1216 = 66.1%,64.4%
gpt-5.4-mini,800,501/800 = 62.6%,63.6%
Qwen3.5-9B,1424,655/1424 = 46.0%,45.8%

That chance baseline is high because the n=5 fill-ins for a step are often not diverse at all -- worth quantifying directly: how often are two fill-ins literally the same code?

In [34]:
# Reuses BASELINE_DIR, N5_DIRS, pickle, pd and display from the cells above.
from collections import Counter
from math import comb

dup_rows = []
for model, pkl_dir in N5_DIRS.items():
    total_steps = 0
    steps_any_dupe = 0
    steps_all_same = 0
    unique_fracs = []
    pairwise_collision = []
    for f in pkl_dir.glob("*.pkl"):
        with open(f, "rb") as fh:
            r = pickle.load(fh)
        for step in r.get("steps", []):
            cands = step.get("candidates") or []
            if len(cands) < 2:
                continue
            codes = [c.get("code") for c in cands]
            n = len(codes)
            counts = Counter(codes)
            total_steps += 1
            steps_any_dupe += int(max(counts.values()) > 1)
            steps_all_same += int(len(counts) == 1)
            unique_fracs.append(len(counts) / n)
            same_pairs = sum(comb(g, 2) for g in counts.values())
            pairwise_collision.append(same_pairs / comb(n, 2))
    dup_rows.append({
        "Model": model,
        "Steps": total_steps,
        ">=1 duplicate": f"{steps_any_dupe / total_steps:.1%}",
        "All n identical": f"{steps_all_same / total_steps:.1%}",
        "Mean unique-fraction (unique codes / n)": f"{sum(unique_fracs) / len(unique_fracs):.1%}",
        "Pairwise collision prob (2 random candidates identical)": f"{sum(pairwise_collision) / len(pairwise_collision):.1%}",
    })

print("=== How often are the n=5 fill-ins for a step literally the same code? ===")
print("Pairwise collision prob = if you pick two of the five fill-ins at random from the same")
print("step, how often are they the exact same code -- this is what drives the duplicate-aware")
print("chance baseline in the cell above; low sampling diversity, not correlation between the")
print("prior and the judge, explains most of that baseline's size.")
display(pd.DataFrame(dup_rows).set_index("Model"))

=== How often are the n=5 fill-ins for a step literally the same code? ===
Pairwise collision prob = if you pick two of the five fill-ins at random from the same
step, how often are they the exact same code -- this is what drives the duplicate-aware
chance baseline in the cell above; low sampling diversity, not correlation between the
prior and the judge, explains most of that baseline's size.

,Steps,>=1 duplicate,All n identical,Mean unique-fraction (unique codes / n),Pairwise collision prob (2 random candidates identical)
Model,,,,,
gpt-4o,1216,76.1%,45.4%,51.6%,55.0%
gpt-5.4-mini,800,84.6%,39.9%,49.3%,54.5%
Qwen3.5-9B,1424,51.9%,21.4%,71.2%,31.0%

## Expectation judge vs the default scores judge, n=5 (2026-09-14/15)

Wired `judge_strategy="expectation"` into `TraceletCodeAgent` (one judge call per candidate, asking whether its observation achieved what its own thought expected -- see `src/smolagents/context_pruning/completion_judge.py`'s `judge_step_achieved_expectation`). Offline it looked far more discriminating than the default 0-10 `"scores"` judge (ESS/n real-discrimination rate 20% vs 3.9%, 0.528 correlation with eventual trajectory success when averaged per trajectory -- see TODO.md). This checks whether that translates into real GAIA accuracy. Qwen3.5-9B is still running as of this cell; only gpt-4o and gpt-5.4-mini are in below.

In [ ]:
# Reuses BASELINE_DIR, mcnemar, pickle, pd and display from the cells above.

EXPECTATION_DIRS = {
    "gpt-4o": BASELINE_DIR / "tracelet_direct_n5_tp_exp5_react_gpt-4o",
    "gpt-5.4-mini": BASELINE_DIR / "tracelet_direct_n5_tp_exp5_react_gpt-5.4-mini",
    # Qwen3.5-9B still running as of this cell -- add once tracelet_direct_n5_tp_exp5_react_Qwen/Qwen3.5-9B hits 165/165.
}
SCORES_DIRS = {
    "gpt-4o": BASELINE_DIR / "tracelet_direct_n5_tp_v6n5_react_gpt-4o",
    "gpt-5.4-mini": BASELINE_DIR / "tracelet_direct_n5_tp_v6n5_react_gpt-5.4-mini",
}


def load_rows(pkl_dir, n):
    rows = []
    for i in range(n):
        with open(pkl_dir / f"{i}.pkl", "rb") as f:
            rows.append(pickle.load(f))
    return rows


expectation_rows = []
for model in EXPECTATION_DIRS:
    scores_dir, exp_dir = SCORES_DIRS[model], EXPECTATION_DIRS[model]
    n = min(contiguous_prefix(scores_dir), contiguous_prefix(exp_dir))
    scores_correct = correctness(scores_dir, n)
    exp_correct = correctness(exp_dir, n)
    s_only, e_only, p = mcnemar(scores_correct, exp_correct)
    scores_rows_data, exp_rows_data = load_rows(scores_dir, n), load_rows(exp_dir, n)
    expectation_rows.append({
        "Model": model,
        "Questions": n,
        "Scores judge accuracy": f"{sum(scores_correct)}/{n} = {sum(scores_correct) / n:.1%}",
        "Expectation judge accuracy": f"{sum(exp_correct)}/{n} = {sum(exp_correct) / n:.1%}",
        "Discordant (scores/expectation)": f"{s_only}/{e_only}",
        "McNemar p": f"{p:.3f}",
        "Scores tokens/q": f"{sum(r['token_counts']['total_tokens'] for r in scores_rows_data) / n:,.0f}",
        "Expectation tokens/q": f"{sum(r['token_counts']['total_tokens'] for r in exp_rows_data) / n:,.0f}",
        "Scores steps/q": f"{sum(r['num_steps'] for r in scores_rows_data) / n:.2f}",
        "Expectation steps/q": f"{sum(r['num_steps'] for r in exp_rows_data) / n:.2f}",
    })

print("=== Expectation judge vs scores judge, n=5 ===")
print("Neither discordant gap is significant (both p > 0.4) -- offline discrimination advantage")
print("did not translate into a detectable real-accuracy improvement, and the expectation judge")
print("costs somewhat more in steps (and, for mini, tokens).")
display(pd.DataFrame(expectation_rows).set_index("Model"))

Temperature of sampling from OpenAI to increase diversity
Number of samples to know how many path downwards
Probability for thought and action template
Probability for numbers in simple Python code without tool call

Checkpoints from the bigger model
Get time of the runs
Run for n=5, n=10 if the performance is too bad, diagnose the judge
---------------
Get probabilities for the code - to infer fi they are same or not.
----------------
Setup baseline for a coding agent

Ok, so now that we have competitive performance, let's try getting numbers out for n=3 and check if it is performing ideally bug free t

In [27]:
# Reuses BASELINE_DIR, mcnemar, pickle, pd and display from the cells above.
import statistics

N3_ARMS = {
    "gpt-4o": (
        BASELINE_DIR / "naive_react_gpt-4o_False_fixedbrowser",
        BASELINE_DIR / "tracelet_direct_n1_tp_v5_react_gpt-4o",
        BASELINE_DIR / "tracelet_direct_tp_v5n3_react_gpt-4o",
    ),
    "gpt-5.4-mini": (
        BASELINE_DIR / "naive_react_gpt-5.4-mini_False_fixedbrowser",
        BASELINE_DIR / "tracelet_direct_n1_tp_v5_react_gpt-5.4-mini",
        BASELINE_DIR / "tracelet_direct_tp_v5n3_react_gpt-5.4-mini",
    ),
    "Qwen3.5-9B": (
        BASELINE_DIR / "naive_react_Qwen/Qwen3.5-9B_False_fixedbrowser",
        BASELINE_DIR / "tracelet_direct_n1_tp_v5_react_Qwen/Qwen3.5-9B",
        BASELINE_DIR / "tracelet_direct_tp_v5n3_react_Qwen/Qwen3.5-9B",
    ),
    "Qwen3.7-Plus": (
        BASELINE_DIR / "naive_react_Qwen/Qwen3.7-Plus_False_fixedbrowser",
        BASELINE_DIR / "tracelet_direct_n1_tp_v5_react_Qwen/Qwen3.7-Plus",
        BASELINE_DIR / "tracelet_direct_tp_v5n3_react_Qwen/Qwen3.7-Plus",
    ),
}


def _load(pkl_dir, indices):
    out = {}
    for i in indices:
        with open(pkl_dir / f"{i}.pkl", "rb") as f:
            out[i] = pickle.load(f)
    return out


n3_rows = []
for model_name, (naive_dir, n1_dir, n3_dir) in N3_ARMS.items():
    if not all(d.exists() for d in (naive_dir, n1_dir, n3_dir)):
        continue
    have = [{int(p.stem) for p in d.glob("*.pkl")} for d in (naive_dir, n1_dir, n3_dir)]
    shared = sorted(set.intersection(*have))
    if not shared:
        continue
    naive, n1, n3 = (_load(d, shared) for d in (naive_dir, n1_dir, n3_dir))
    # A provider error scores as incorrect, so keep only questions clean in all three arms.
    keep = [i for i in shared if not any(arm[i].get("error") for arm in (naive, n1, n3))]
    row = {"Model": model_name, "n": len(keep), "n=3 done": f"{len(have[2])}/165"}
    for label, arm in (("naive", naive), ("n=1", n1), ("n=3", n3)):
        correct = sum(1 for i in keep if arm[i].get("is_correct"))
        row[f"{label} Acc"] = f"{correct}/{len(keep)} = {correct / len(keep):.1%}"
        row[f"{label} Steps"] = f"{sum(arm[i].get('num_steps', 0) for i in keep) / len(keep):.1f}"
        row[f"{label} MedTok"] = f"{statistics.median(arm[i]['token_counts']['total_tokens'] for i in keep):,.0f}"
    tok1 = sum(n1[i]["token_counts"]["total_tokens"] for i in keep)
    tok3 = sum(n3[i]["token_counts"]["total_tokens"] for i in keep)
    row["n=3/n=1 Tokens"] = f"{tok3 / tok1:.2f}x" if tok1 else "-"
    flags = {k: [bool(arm[i].get("is_correct")) for i in keep] for k, arm in
             (("naive", naive), ("n1", n1), ("n3", n3))}
    x, y, p = mcnemar(flags["n1"], flags["n3"])
    row["n=1 vs n=3"] = f"{x}/{y}"
    row["p (n=1 vs n=3)"] = f"{p:.3f}"
    x, y, p = mcnemar(flags["naive"], flags["n3"])
    row["p (naive vs n=3)"] = f"{p:.3f}"
    row["Errors n/1/3"] = "/".join(
        str(sum(1 for i in shared if arm[i].get("error"))) for arm in (naive, n1, n3)
    )
    n3_rows.append(row)

print("=== Best-of-n: naive vs Probabilistic ReAct n=1 vs n=3 ===")
print("Matched, error-free subsets. Qwen runs were stopped early, so their n is smaller.")
display(pd.DataFrame(n3_rows).set_index("Model"))

=== Best-of-n: naive vs Probabilistic ReAct n=1 vs n=3 ===
Matched, error-free subsets. Qwen runs were stopped early, so their n is smaller.

,n,n=3 done,naive Acc,naive Steps,naive MedTok,n=1 Acc,n=1 Steps,n=1 MedTok,n=3 Acc,n=3 Steps,n=3 MedTok,n=3/n=1 Tokens,n=1 vs n=3,p (n=1 vs n=3),p (naive vs n=3),Errors n/1/3
Model,,,,,,,,,,,,,,,,
gpt-4o,160,165/165,53/160 = 33.1%,8.3,"30,484",41/160 = 25.6%,12.4,"116,276",43/160 = 26.9%,10.6,"99,946",0.86x,17/19,0.868,0.154,0/0/5
gpt-5.4-mini,165,165/165,53/165 = 32.1%,5.0,"11,122",55/165 = 33.3%,7.7,"61,784",61/165 = 37.0%,7.0,"61,313",1.00x,13/19,0.377,0.280,0/0/0
Qwen3.5-9B,126,134/165,58/126 = 46.0%,16.9,"110,410",59/126 = 46.8%,18.5,"232,355",57/126 = 45.2%,19.1,"303,138",1.22x,19/17,0.868,1.000,0/0/8
Qwen3.7-Plus,163,165/165,108/163 = 66.3%,16.0,"108,063",100/163 = 61.3%,17.0,"212,188",105/163 = 64.4%,17.2,"153,342",0.68x,13/18,0.473,0.701,1/0/1

TODOs:
1. Get the probabilities out
    a. Expected number of steps 1/p
       Under the assumption that every call is independent 1/p
       
       Outer loop indpendent model calls, an independent while loop inside,
       If the judge is correct, 

       Link to verifying the number of steps needed in naive ReAct, expected number of steps 
       n and judge  lets you know the probability of success
       expected number of steps
2. Run any of these models 3 times to see what the variance is
3. Truncation in the web page, visiting to see if the lack of information is causing looping
4. Check if the format of the fill in is the thing getting messed up
5. The format of code template and fill in might be difficult

Ok, so it seems that we are now getting competitive accuracy for gpt5.4 mini, Qwen3.5-9B and Qwen3.7-Plus. However gpt5.4 mini uses 6.3x tokens. The high number of tokens can be explained as 3 x (7.7/5)^2 = 7.1148 > 6.3 but we do not see this behaviour in other models so it is suspicious why this is happening.

I am moving on to getting results for n=3 anyways. Changes motivated by n=3
1. Blocking URLs that can leak the answer for GAIA dataset
2. Fixing capturing of the state properly in the web browser

TODOs:
1. Debug gpt5.4 mini token usage bloat
    - Shut off thinking tokens (using the openai link)
    - can experiment with gpt4.1 mini in the worst case
2. Get all the models run upto 165
3. Setup a local LLM server on DGXSpark (ask Varsha)
    - vllm with smolagents
    - you can get logprobs from vllm
        - full logprbs by setting logprobs=-1
4. Get probabilities out
5. Run n=3

Clearly there is a significant drop in accuracy for TraceletReAct. There are few possible reasons for this:
1. Making the model output the template is decreasing its performance
2. Model is failing to output the fillins for all sentinels in a template

To isolate these effects, I am running experiments with n=1 and the accuracy should be strictly less than n=3

Human Notes:
- TODO: extracting probability for the actions (you can get from OpenAI or TogetherAI)
- formal questions about how they are helping in modeling
- reflexion - more concretely, the model generates a unit test
    - do we want to output observes and use them to guide feedback
- Question: which thing need probability - action output, feedback should be probability
    - how do you interpret it
    How often is the solution ranked one
    How often are we consistent - is the judge sucks
        Formally, we are saying that the probabilty of generation should correlate with probability of judging the option to be the most correct
        Light version of verification
        Verification of language model programming
    The judge sucks - we can signal that 

- Added structure to have probabilistic structure to diagnose models
    - Is the first solution better than the second solution
    - If the model is good, than it should rank things according to score
    - Language model judge should point to the most correct solutions - verifying the judge
    - We can measure stuff and these are the things we can measure
        - We don't lose performance over Vanilla ReAct
        - We improve performance
        - We can also optimize the programs to increase performance and efficiency


By the end of this month,
- have a prototype of probabilistic ReAct
- empirical results of GAIA and maybe Fermi, and maybe some other dataset
- plugin to the language Kyle is building 
    - pluginto tensors and circuits
- traces, analysis
        -

At full scale (165/165 for all three models), the picture doesn't support the "best-of-n should be strictly better" hypothesis above: Tracelet (direct_prompt) comes out roughly flat or behind naiveReAct on accuracy for every model, at meaningfully higher token cost (~2.5x for gpt-4o, ~8x for gpt-5.4-mini, roughly even for Qwen3.5-9B) and more steps across the board.

Before reading too much into the accuracy gaps, though: these are single runs per condition, and this exact naiveReAct setup is already documented above as varying significantly run to run. Rough two-proportion check (n=165 each): gpt-4o's gap is ~1 question, indistinguishable from noise. gpt-5.4-mini's ~6.7pp gap is ~1.3 standard errors, still plausibly noise. Qwen3.5-9B's ~12.7pp gap is ~2.3 standard errors -- looks like a real signal, but it's still one run against one run, so treat it as suggestive, not conclusive, without repeats.

Manually inspecting several trajectories also surfaced a real bug worth fixing before trusting these numbers much further: when the model's fill-in response for a sentinel doesn't match the expected `<sentinel>: <value>` line format exactly (e.g. wrapped in backticks or a leading bullet), `_parse_fillin_lines` silently drops that line and the sentinel is left unsubstituted in the code. If the judge then scores all `n` candidates identically (e.g. because none made real progress), `_pick_best`'s tie-break defaults to candidate 0 regardless of whether it's actually viable -- so a candidate with a literally unresolved sentinel variable can still get committed and executed, surfacing as `InterpreterError: The variable ARG0 is not defined`. Seen this twice independently across the trajectories inspected so far (not a fluke) -- not yet fixed. Fix: make `_pick_best` deprioritize/exclude candidates whose trial observation started with `"Error:"` instead of treating them as tie-eligible.

## Related Work

[Self Compacting Language Model Agents](https://arxiv.org/pdf/2604.17290) prompts a language model to fill up a rubric and decided to compress or not every N steps in order to deal with context rot and ever increasing context. 
- Can be a good place to check for alternate datasets

[PPDL](https://arxiv.org/abs/2608.05234) has built a probabilistic programming language for language model prompting. It provides a framework where people can provide the prompt for the language model and provide constraints (hard syntactic constraints or soft LLM-as-a-judge constraints) using the factor construct. Using this framework they show how IS and SMC can be used as inference algorithms in this flow. Very similar to [Encompass](https://arxiv.org/pdf/2512.03571) but with probabilities. 

In this [paper](https://arxiv.org/pdf/2512.04469), the authors tried to come up with a probabilistic framing of ReAct, multi agent systems, tree of thought and many other things. However, they simply come up with the framework and never do anything with it. It reads more like a survey paper unfortunately.

Fermi is less markovian where it can be harder to do better than naive truncation
Establish baselines to reduce token budget effectively
Open weight models are performant and still have room to improve.
s

# Context Pruning ReAct Agent

I wonder if the following pseudocode makes sense:

```python
system_prompt = ...
task = ...
is_final = False
memory = system_prompt + task
submemory = ``
while not is_final:
    thought, action, observation = LLM(. | memory + submemory)
    is_final = check(action)
    if is_final:
		answer = extract_answer(action)
	else:
        result = execute(action)
        complete = LLM(. | thought, action, result, observation, "Is the observation satisfied in this result?")
        if complete:
            memory += thought + action + observation + result
            submemory = ``
        else:
            submemory += thought + action + observation + result
return answer
```